### ISSUE TITLE
[BUG] Speedtest soped working anymore [No Eula Issue]

### ISSUE THREAD

**Issue by nixmomo** [henrywhitaker3/Speedtest-Tracker#1052]
**Describe the bug**
After try to start a test in the docker container i get this error
![image](https://user-images.githubusercontent.com/8502506/187936727-dd0d1a52-a1b5-414f-a352-9f2d9f2179f6.png)

**To Reproduce**
1. Go to webinterface
2. Click on Test start

**Expected behavior**
Speedtest should run

**Log**

      
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing... 
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-speedtest: executing... 
s6-applyuidgid: fatal: unable to exec /site/app/Bin/speedtest: No such file or directory
Copying latest site files to config
Database file exists
Env file exists
Updating packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/1) Installing composer (2.1.9-r0)
Executing busybox-1.33.1-r3.trigger
OK: 164 MiB in 176 packages
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-ide-helper
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: henrywhitaker3/laravel-actions
Discovered Package: laravel-notification-channels/telegram
Discovered Package: laravel/slack-notification-channel
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: tymon/jwt-auth
Package manifest generated successfully.
90 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Running database migrations
Nothing to migrate.
App key exists
JWT secret exists
Slack webhook is unset
Telegram chat id and bot token unset
Base path is unset
AUTH variable not set. Disabling authentication
Disabling authentication
Clearing old jobs from queue
[cont-init.d] 50-speedtest: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/config/www/app/Bin/speedtest: line 1: syntax error: unexpected word (expecting ")")

**Context**
 - OS: [e.g Docker, Ubuntu, etc.]
 - Speedtest-Tracker Version: 

**Additional context**

**Comment by tgkenney** [comment]
I don't see any EULA issues in your logs, but I do see an issue with the GeoIP database which was the same error I was getting.  I was able to resolve that error and the app has been running successfully since.  The fix for me was to download the `GeoLite2-City.mmdb` database, and then mount the folder that file is in at `/config/geoip2db/` 

The app has been successfully running for me since I did this

**Comment by nixmomo** [comment]
hmm i tried this but it has not fixed the issue

**Comment by nixmomo** [comment]
ahh... i deleted the speedtest file in www/app/Bin/ and he downloaded the file again... now it is working as expected
