### ISSUE TITLE
[Feature Request] Add read-only switch to allow for external access without auth

### ISSUE THREAD

**Issue by jd3shaw** [henrywhitaker3/Speedtest-Tracker#1070]
**Describe the feature**
It would be great if it were possible to configure this docker image locally, then add a switch into the Docker env to disable all the configuration options. Then it should be possible to allow external access without worrying about authentication. Just to monitor or show internet speed over time.

**Additional context**
I'd like to be able to share a link to the speedtest tracker page and allow others to view the results without authentication. If they are authenticated (I assume) they will be able to change the settings, which is not what I want. This would be handy when showing ISP of significant speed fluctuations/discrepancies.

**Comment by spcqike** [comment]
Hi there

Maybe you want to post your request in the active fork 
https://github.com/alexjustesen/speedtest-tracker

**Comment by jd3shaw** [comment]
@spcqike will do, thanks
