### ISSUE TITLE
Used docker image website loads on 0.0.0.0:32769 but start your first test or any other command not working

### ISSUE THREAD

**Issue by harssh** [henrywhitaker3/Speedtest-Tracker#110]
![Screen Shot 2020-06-19 at 10 09 07 AM](https://user-images.githubusercontent.com/2812994/85147848-08ce0c00-b215-11ea-896f-5f210bbed6cc.png)

Using this command to run docker image

docker run -d -P --name speedtest-tracker henrywhitaker3/speedtest-tracker

**Comment by henrywhitaker3** [comment]
Yeah just had a go and it's a db permissions issue. Restart the container created from that `run` command and it will work. 

A new image with fixes is building on docker hub now so give it 10 mins and pull the new image.

**Comment by harssh** [comment]
Yep new docker image is working as expected.

**Comment by henrywhitaker3** [comment]
Nice one
