### ISSUE TITLE
[Feature Request] Push version tag in DockerHub

### ISSUE THREAD

**Issue by matbrgz** [henrywhitaker3/Speedtest-Tracker#1102]
**Describe the feature**
![image](https://user-images.githubusercontent.com/23284276/207943626-01f362c4-aceb-4f16-a26f-ac62cb144d4f.png)

We are trying to use the Speedtest-Tracker within Umbrel https://github.com/getumbrel/umbrel-apps/pull/279. Umbrel is an OS for running a personal server in your home.
We need that this repository push in docker the version use the tag to fix the version.

**Comment by IMPranshu** [comment]
I have implemented this. You can find the image at https://hub.docker.com/repository/docker/impranshu/speedtest/tags?page=1&ordering=last_updated

I have also opened a PR with this change in the Umbrel https://github.com/getumbrel/umbrel-apps/pull/678
<img width="1488" alt="Screenshot 2023-07-11 at 11 38 00 AM" src="https://github.com/henrywhitaker3/Speedtest-Tracker/assets/43396684/e235c2bb-663e-468f-8b27-4cbd857ca6d7">
