### ISSUE TITLE
Trying to get property 'ping' of non-object

### ISSUE THREAD

**Issue by stewartjustind** [henrywhitaker3/Speedtest-Tracker#111]
Hello,

I've had this issue while doing a manual install on a proxmox 18.04 ubuntu container. After running the commands as instructed, while running the php artisan speedtest:run command I get the following error:

```
  ErrorException 

  Trying to get property 'ping' of non-object

  at app/Console/Commands/SpeedtestCommand.php:45
    41|         $this->info('Running speedtest, this might take a while...');
    42| 
    43|         $results = SpeedtestHelper::runSpeedtest();
    44| 
  > 45|         $this->info('Ping: ' . $results->ping . ' ms');
    46|         $this->info('Download: ' . $results->download . ' Mbit/s');
    47|         $this->info('Upload: ' . $results->upload . ' Mbit/s');
    48|     }
    49| }

  1   app/Console/Commands/SpeedtestCommand.php:45
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Trying to get property 'ping' of non-object", "/var/www/Speedtest-Tracker/app/Console/Commands/SpeedtestCommand.php", [])

      +14 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

Not sure how to go about fixing it, only thing I have done different is that I had to include php7.2-mbstring in the dependencies otherwise the composer was failing.

**Comment by henrywhitaker3** [comment]
Okay, will make sure to update the readme with mbstring.

What version of speedtest-tracker are you using? Does it run a speedtest correctly through the UI?

When I have some time later I'll spin up an 18.04 VM and see if I can reproduce the issue

**Comment by stewartjustind** [comment]
speedtest-cli --version output:
```
speedtest-cli 2.1.2
Python 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```
It runs correctly, but every once in a while it fails with a malformed URL exception or cannot retrieve speedtest configuration. I installed speedtest via the pip3 install command in readme. I thought that the speedtest-cli error every once in a while might be causing the issue so I tried it multiple times, still the same error.

**Comment by henrywhitaker3** [comment]
Ah I meant the speedtest-tracker version

**Comment by stewartjustind** [comment]
Oh, I pulled from the master branch.

**Comment by henrywhitaker3** [comment]
When u open the page in a browser, scroll right to the botto and it should display a version number

**Comment by stewartjustind** [comment]
Yah let me check that. I havn't even gotten that far, was just doing the "php artisan speedtest:run" command to test if it works when I got the error so that stopped my progression a little bit. I should still be able to load the page though.

**Comment by henrywhitaker3** [comment]
Ah fair enough. There any reason you're not using the docker image? Will just work without having to do anything manually.

I'd suggest pulling from the `dev` branch for a manual install at the moment as I've moved away from using the speedtest-cli package to Ookla's cli

**Comment by stewartjustind** [comment]
No reason really, running most stuff out of proxmox containers and the last time I tried to setup a docker container it was a PITA through proxmox. I will give the dev branch a try and see if that helps.

**Comment by henrywhitaker3** [comment]
Ah fair enough, I hadn't used docker until I made the image for this project. Now just have a VM with a lot of CPU and RAM in proxmox running docker with a few lxc containers running anything that isn't on docker.

For the newest `dev` version for a manual install you'll likely have to run the following first time:

```bash
sudo -i -u www-data
```

```bash
/path/to/speedtest-tracker/app/Bin/speedtest
```

First time it runs you just have to accept the EULA then it should be good to go

**Comment by stewartjustind** [comment]
Awesome! I will give it a shot and if that doesn't work I will probably just install via docker.

**Comment by stewartjustind** [comment]
Well, I just went with the docker image since it was MUCH easier. Although I am having inconsistencies in the download speed - but I see there is another issue with that one being logged so I will jump over to that discussion and close this issue. Thanks for the help!
