### ISSUE TITLE
Double Test

### ISSUE THREAD

**Issue by psycor** [henrywhitaker3/Speedtest-Tracker#112]
Hello,
i use this tool in an optimized Docker version under Unraid. Every full hour it does not only run one test, but with an interval of about 30 seconds, it runs 2 tests at the same time. This gives me a very shifted diagram.
Under all test results i can see e.g. 05:00:34 and 05:00:53 one test contains a high value and the other the corresponding lower value. If i add both values, the final result fits to my real internet connection speed.

![sample](https://user-images.githubusercontent.com/21679267/85199340-fde7aa00-b2ee-11ea-8f47-f2d9945e4bb1.PNG)

![diagram](https://user-images.githubusercontent.com/21679267/85199370-430bdc00-b2ef-11ea-861a-366af3244d67.PNG)
This is not a nice curve because of the double tests.

**Comment by henrywhitaker3** [comment]
That's really weird, it shouldn't even be possible to run 2 tests at the same time, they should just queue. Could you try switching the image to `henrywhitaker3/speedtest-tracker:dev` to see if this fixes the problem?

**Comment by psycor** [comment]
Hello,
I do a full fresh install of the docker with new image henrywhitaker3/speedtest-tracker:dev and new variable OOKLA_EULA_GDPR = true....
Now waiting for automatic testruns...

THX so far

**Comment by henrywhitaker3** [comment]
No worries, you should be able to force it to run a scheduled test by updating the schedule setting:

![2020-06-20_16-31](https://user-images.githubusercontent.com/36062479/85205501-9859e480-b313-11ea-8cf5-6e503970afd7.png)

**Comment by psycor** [comment]
Hi after the last 2 autotests it seems ok one at 5pm and one at 6pm !
Will report if change

THX

**Comment by henrywhitaker3** [comment]
Nice one
