### ISSUE TITLE
[BUG] Admin Login redirects me to login page once again

### ISSUE THREAD

**Issue by AlexFigas** [henrywhitaker3/Speedtest-Tracker#1141]
**Describe the bug**
When  I try to login with the default admin password I get redirected to this screen once again.

**To Reproduce**
1. Go to your ip to access the web-ui, in my case http://192.168.1.87:8081/
2. Click on Sign In / Admin Panel
3. Login

**Expected behavior**
Log in and get to this page:

**Screenshots**
This is the screen I get redirected to:
![image](https://github.com/henrywhitaker3/Speedtest-Tracker/assets/65889776/76637842-77b2-4065-b81a-8368ebfe1b9a)

This is the screen I should get after login:
![dashboard_screenshot](https://github.com/henrywhitaker3/Speedtest-Tracker/assets/65889776/aaa88e16-991e-4e4d-a7ac-e6b39e624e41)

**Context**
 - OS: Docker
 - Speedtest-Tracker Version: latest

**Comment by balintbabics** [comment]
I think your screenshots are from another speedtest tracker application - from Alex Justesen, not from Henry Whitaker, so it would be better to post your issue there.

**Comment by AlexFigas** [comment]
Oops
