### ISSUE TITLE
[Feature Request]Telegram integration and Server-Selection

### ISSUE THREAD

**Issue by psycor** [henrywhitaker3/Speedtest-Tracker#118]
Hello,
It would be very nice if there were a setting option where you could choose all servers and test them there for connection quality. So you would have a better possibility to choose the servers that are relevant for the monitoring. I have found out only now with the dev builds that you have to enter the ID of the server for the server configuration. If I had a list of servers and their connection quality, I could simply check the boxes of the servers that are allowed to use the monitoring.

In the same way I would find a further integration for the telegram messenger very helpful.

I hope I explained it understandable, my english is not the best, because I learned it only rudimentary in the past. Thanks for this great project.

I Hope it ist the right place to requests it here.

**Comment by henrywhitaker3** [comment]
So you don't *have* to put a server ID in the settings. If you leave it blank, it will automatically choose the best server. I suppose down the line I could add a list but this wouldn't be a priority, as you can see the lists of server on the speedtest.net site.

Yeah I'll get working on telegram in the next day or two. I'll comment again here when it's in `dev`

**Comment by psycor** [comment]
The problem is that my automatically selected servers were very bad. So I always had bad values in between. In the overall list I could find the best server now by the new entry of the Servere-ID and enter this manually in the settings.
It's just an idea to provide a list here with e.g. the first 10-20 closest server with its test results and ID.
So you could see which servers in the area are good and which are bad.

**Comment by henrywhitaker3** [comment]
Generating that list using their cli would use up a lot of bandwidth, so I don't think I'm going to do that. You can use the cli manually to find the IDs of servers that do give you good results and then add those IDs comma separated into the server setting field.

E.g. Say you get good results from IDs: 1, 2 and 3

Set your server id setting to `1,2,3`

Now when a speedtest is run, it will randomly pick from those 3 servers.

The telegram notifications are done now though, if you've done manual install, it is the `dev` branch, or for docker the changes will be in the `dev` tag on dockerhub
