### ISSUE TITLE
Discord notifications?

### ISSUE THREAD

**Issue by Tharic99** [henrywhitaker3/Speedtest-Tracker#135]
So I see you mention telegram and slack notifications and the docs and the wiki both have the environment info for them on the docker container, but I don't see what the environment info would be for discord notifications.

Any info?

Thanks!

**Comment by henrywhitaker3** [comment]
For discord just use the slack env variable but pop `/slack` onto the end of the discord webhook and it should work fine

**Comment by Tharic99** [comment]
Perfect. Worked like a champ. Thanks!

**Comment by calebcaudill** [comment]
I just tried to implement this by putting /slack at the end of my Discord Webhooks and it is not working. If it matters, I am using the notification settings in the gui.

**Comment by DJScias** [comment]
> I just tried to implement this by putting /slack at the end of my Discord Webhooks and it is not working. If it matters, I am using the notification settings in the gui.

Hello there,

This is what I currently use for webhook on Discord and it works just fine. Maybe you changed the url a bit? Or the webhook didn't save on Discord?

![image](https://user-images.githubusercontent.com/439655/123076458-73fa8180-d419-11eb-8f95-2d34ab93193a.png)
(The blurred part is just the long string discord generates unique to your webhook)
