### ISSUE TITLE
[BUG] Doesn't report when there is an outage/error

### ISSUE THREAD

**Issue by JesseyWhite** [henrywhitaker3/Speedtest-Tracker#143]
**Describe the bug**
This program is set up in my docker and I have it cron job every hour on the hour. When there is an internet outage, it gives no reports of one. It will skip and move on until there is a valid test. 

**To Reproduce**
1. Setup the program with a cron job
2. Run a valid speed test
3. Once step 2 shows a valid speed test, disconnect internet
4. Run a speed test
5. Once step 4 is complete, connect internet
6. Run speed test
7. Here you will only see results from steps 2 and 6, with step 4 not showing.

**Expected behavior**
The program should report speed test results as error or 0. If there is fear that false reports may show up, then have the program ping a server that is known to have excellent uptime such as 8.8.8.8 or 1.1.1.1 to confirm that a connection is online or offline. 

**Screenshots**
https://i.imgur.com/qRo7qCS.png
https://i.imgur.com/g2tKIxv.png

**Context**
 - OS: Docker in Unraid
 - Speedtest-Tracker Version: 1.7.1

**Additional context**
I used this program to be able to keep a record of my ISP uptime and speed. I assumed that if the internet goes out, it would be reported in the program, but it does not. Therefore unless this is fixed I will not be able to recommend this program to peers.

Let me know if you need more info

**Comment by JesseyWhite** [comment]
[speedtest_backup_2020-07-03_08_15_21.zip](https://github.com/henrywhitaker3/Speedtest-Tracker/files/4868619/speedtest_backup_2020-07-03_08_15_21.zip)

https://i.imgur.com/iE9oPX9.png

Here is my data. I hope it helps!

**Comment by henrywhitaker3** [comment]
Yeah this is a good point and have started working on it. I'll let you know when there's an update to the docker image.

**Comment by henrywhitaker3** [comment]
Right, changes have been built into the `dev` tag
