### ISSUE TITLE
[BUG] CRON settings being ignored

### ISSUE THREAD

**Issue by OFark** [henrywhitaker3/Speedtest-Tracker#148]
**Describe the bug**
Despite my CRON job setting being 0 * * * * the speed-test is running every minute.

**To Reproduce**
1. Save the CRON settings
2. Restart the Docker

**Expected behaviour**
A job to run every hour.

**Context**
 - OS: UNRAID Docker
 - Speedtest-Tracker Version: 1.7.1

**Additional context**
 Before this latest update, it wasn't running a CRON job regularly at all, now it's running it too often.

**Comment by OFark** [comment]
Log file: https://pastebin.com/9rY7Zmzv

**Comment by henrywhitaker3** [comment]
Okay, from the logs it looks like it might be retrying a speedtest after it fails.

I think it would be useful for you to see why these speedtests are failing in the first place. Get a shell in the running container:

```bash
 docker exec -it speedtest bash
```

Then manually run the speedtest binary:

```bash
HOME=/config && /config/www/app/Bin/speedtest
```

and see what errorsit gives you and figure out why your speedtests are failing.

**Comment by OFark** [comment]
I will try that in a bit, but in the mean time: it is showing successful results. I will still do the test though.

**Comment by OFark** [comment]
https://pastebin.com/jazpTL5t
As far as I can see no errors. I ran it 3 times to be sure. Interesting that last time has no results URL. That wasn't left out intentionally.

**Comment by OFark** [comment]
Further note; I have refreshed the results and it seems to have stopped testing, shortly after I started this ticket. No tests at all, not even on the hour. After the log from the original post there are only two more lines:

{"type":"log","timestamp":"2020-07-05T11:52:56Z","message":"Error: [110] Cannot open socket: Timeout occurred in connect.","level":"error"}

{"type":"log","timestamp":"2020-07-05T11:53:48Z","message":"Error: [11] Cannot read: Resource temporarily unavailable","level":"error"}

End of Log.

**Comment by henrywhitaker3** [comment]
Hmm that's weird. Can you try re-creating the container using the `dev` tag?

**Comment by OFark** [comment]
> Hmm that's weird. Can you try re-creating the container using the `dev` tag?

How, exactly?

**Comment by henrywhitaker3** [comment]
How have you setup the container to start with?

**Comment by OFark** [comment]
It's a docker with UNRaid.
`docker run -d --name='speedtest-tracker' --net='bridge' -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'SLACK_WEBHOOK'='' -e 'OOKLA_EULA_GDPR'='true' -p '28888:80/tcp' -v '/mnt/disks/M2/appdata/speedtest-tracker':'/config':'rw,slave' --restart unless-stopped 'henrywhitaker3/speedtest-tracker' 
6320f830adcac556b4e47f009ad050826b2cadba7242bc2e8f87452c6360fd99`

**Comment by henrywhitaker3** [comment]
Okay, not 100% sure on how to do this with the unraid GUI, but you should be able to change the tag by changing `henrywhitaker3/speedtest-tracker` to `henrywhitaker3/speedtest-tracker:dev`

**Comment by OFark** [comment]
Ok, done that, quite simple in unraid. 

So when I got the Docker run command to paste here I had to force a reinstall of the app, this started the minutely testing again. Same as before. However, when I applied the :dev tag, and reinstalled, it carried on doing the tests every minute again but this time the results of the tests flat-lined.  Also, the bash script threw some errors:
https://pastebin.com/4D72FJrc
You can see the point where I installed the dev version where the flat line starts.
![image](https://user-images.githubusercontent.com/4558132/86545049-ac146600-bf23-11ea-8707-70411fabb7c0.png)

**Comment by OFark** [comment]
The log since dev:
https://pastebin.com/9Eu97KsV

**Comment by OFark** [comment]
Ohh I should probably say that I was manually running those tests in bash, whilst the app was flat-lining. As far as I know, I had an internet connection at that time.

**Comment by henrywhitaker3** [comment]
Yeah the `dev` tag logs failed tests as 0, so they're included in the graph. Will be making some changes to stop the failed tests appearing in the graphs tomorrow. 

From that paste in, there's definitely something going wrong with your network, whether that's the docker network or your physical connection, because those errors aren't normal.

I'll quickly set a container to run on unraid and leave it a few hours to see if I can reproduce the errors you're getting.

**Comment by OFark** [comment]
Yeah my ISP is 'upgrading my services' which means I have this piss poor connection. That said, my upload is abysmal, but the download solid. My wife has been attending uni via video conferencing for the last three days and not one complaint. Still, I'm not getting what I've paid for so I'm trying to log it, hence this app.

**Comment by OFark** [comment]
Ahh hah, so the :dev version does appear to be running a test every hour. Flat lines, but I guess that's due to errors. but it doesn't repeat if it fails, just waits for the next hour.

**Comment by henrywhitaker3** [comment]
Sweet, I'll be pushing changes to stop the graphs showing failed tests later today

**Comment by OFark** [comment]
So I've pulled the latest version of :dev and it's running. But it is now testing every 20 seconds, successfully I might add - it appears my ISP has finished. I expect this will stop soon and I hope it'll fall back to once an hour, but I've only just updated it.

**Comment by henrywhitaker3** [comment]
Ah the Dev tag has a Cron job to retry failed queue jobs so it's probably working through all of the previous failed tests. Think I'm going to exclude speedtest jobs from the retry

**Comment by OFark** [comment]
Well, I can report this :dev version does appear to be testing every hour now.

**Comment by OFark** [comment]
Is this still :dev only or has it been migrated to master?

**Comment by henrywhitaker3** [comment]
Just in Dev at the moment, will merge in the next day or two

**Comment by Rustymage** [comment]
Is this fixed?

I still keep getting this error.

`{"type":"log","timestamp":"2020-12-09T19:00:07Z","message":"Error: [11] Cannot read: Resource temporarily unavailable","level":"error"}`


Here is my docker command:

```
version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8765:80
        volumes:
            - ./data:/config
        environment:
            - TZ=EUROPE/LONDON
            - PGID=1000
            - PUID=1000
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
```

**Comment by Rustymage** [comment]
Here are my errors.

```
{"type":"log","timestamp":"2020-12-09T21:00:10Z","message":"Error: [11] Cannot read from socket: Resource temporarily unavailable","level":"error"}


{"type":"log","timestamp":"2020-12-09T23:00:06Z","message":"Error: [110] Cannot open socket: Timeout occurred in connect.","level":"error"}


{"type":"log","timestamp":"2020-12-10T01:00:13Z","message":"Error: [11] Cannot read: Resource temporarily unavailable","level":"error"}
```
