### ISSUE TITLE
[BUG] blinking white dot in page center when behind reverse proxy

### ISSUE THREAD

**Issue by hollanbm** [henrywhitaker3/Speedtest-Tracker#175]
I'm using the linuxserver/letsencrypt reverse proxy to handle ssl, and route to the speedtest monitor site. However, when I put the site behind nginx, the only thing I can see, is a blinking white dot. I'm assuming its a page load indicator. I'm not quite sure why this happens.

I'm using the default bridge network to handle communication between the containers and the reverse proxy. Slightly more secure this way, forces users to login with organizr auth first.

I'm not quite sure what's going on, I'm assuming the blinking dot is a page load indicator.

javascript console
```
Uncaught (in promise) Error: Request failed with status code 404
    exports https://www.mydomain.org/speedtest/files/js/app.js?v=1-7-7:2
    exports https://www.mydomain.org/speedtest/files/js/app.js?v=1-7-7:2
    onreadystatechange https://www.mydomain.org/speedtest/files/js/app.js?v=1-7-7:2
```

docker-compose.yml
```
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker:dev
    expose:
      - 80
    volumes:
        - ${HOME}/Services/SpeedTest:/config
    environment:
        - PUID=1000
        - PGID=1000
        - TZ="America/Kentucky/Louisville"
        - BASE_PATH=/speedtest
        - OOKLA_EULA_GDPR=true
    restart: unless-stopped
```
speedtest.subfolder.conf
```location ^~ /speedtest {
    
    auth_request /auth-4;   #=User

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app speedtest;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}
```

docker logs -f speedtest
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing... 
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-speedtest: executing... 
Copying latest site files to config
Database file exists
Env file exists
Running database migrations
Nothing to migrate.
App key exists
JWT secret exists
Slack webhook is unset
Telegram chat id and bot token unset
Base path set, updating .env
[cont-init.d] 50-speedtest: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
```

**Comment by henrywhitaker3** [comment]
Yeah that's a page loading indicator. Not sure why it's not working for you, I also use org Auth and the letsencrypt container to RP speedtest-tracker with the same base path.

First up, do you know what version of speedtest-tracker you have? If it's not a really old one, you should be able to run 

```bash
php /config/www/artisan speedtest:version
```

Does trying to access the container by IP:port/speedtest bring up the same loading icon? How about just IP:port without the base path?

**Comment by hollanbm** [comment]
```
docker exec -it speedtest /bin/bash
root@62569b2dcd9b:/# php /config/www/artisan speedtest:version
Speedtest Tracker v1.7.7
root@62569b2dcd9b:/# 
```

With my current setup, the letsencrypt container, is the only container with ports mapped (80.443) on the host. The rest of my containers, are attached to the default docker bridge network, and expose ports within the docker network to facilitate communication between them all.

This lets me force all of my users (even local) to go through the reverse proxy, and authenticate with organizr, before accessing the rest of the containers.

With that said, if I map a port on the host, to port 80 in the speedtest container, I can access the site via local IP:Port, and it works as expected.

Is there another port that needs to be exposed? Or do I need to make changes to my nginx config?

Do you know of any other steps I can take for debugging? I'm a little confused as to why I'm seeing this behavior. The rest of the containers I've configured this way, work after the base path url is updated

**Comment by henrywhitaker3** [comment]
Should just be port 80 on the container. I won't have my laptop until tomorrow evening so can't share my nginx config now, although I'm pretty sure I just copied the Monitorr sample config from the letsencrypt container though. Also make sure you are going to domain.com/speedtest/ just to make sure it's not an issue with missing the trailing slash.

In terms of debugging, you could try looking through the output of `/config/www/storage/logs/laravel.log` and see if there's anything interesting there.

I am going to update the container soon to have more verbose logging.

**Comment by hollanbm** [comment]
> Also make sure you are going to domain.com/speedtest/ just to make sure it's not an issue with missing the trailing slash.

/facepalm

This in fact was my problem. When visiting domain.org/speedtest the blinking dot happened. When visiting domain.org/speedtest**/** everything works as expected

**Comment by hollanbm** [comment]
@henrywhitaker3 Now that I have the tab in organizr working appropriately, I am attempting to configure the homepage widget.

I imagine this is a organizr /widget issue but wanted to confirm first.

I have the connection in the widget configured as https://domain.org/speedtest/ - when the homepage loads, the widget briefly shows "loading", and then disappears when finished.

**Comment by henrywhitaker3** [comment]
You're supposed to use local ip:port for a homepage item in org, so I'm guessing it's failing as the backend is failing the nginx auth_request. You can check the Organizr logs in the settings page to see if there's any errors in there

**Comment by hollanbm** [comment]
> You're supposed to use local ip:port for a homepage item in org, so I'm guessing it's failing as the backend is failing the nginx auth_request. You can check the Organizr logs in the settings page to see if there's any errors in there

Thank you so much for your assistance. I was able to get this resolved. I am going to try and submit a PR to the letsencrypt repo to add a default nginx sample config for speedtest-tracker.

For future reference, and assistance with other users. here is what I had to use.


#### nginx speedtest.subfolder.conf
```
# add the following environment variable to the speedtest container
# BASE_PATH=/speedtest
        
location /speedtest {
    return 301 $scheme://$host/speedtest/;
}

location ^~ /speedtest/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /ldaplogin;

    # enable for Authelia, also enable authelia-server.conf in the default site config
    #include /config/nginx/authelia-location.conf;

    auth_request /auth-4;   #=Admin

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app speedtest;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}
```

#### Homepage
```Connection: localip:port/```

#### Tab
https://domain.org/speedtest



with my particular config, since I am using the docker default bridge network (and not exposing a port on the host), instead of using localip:port - I can access the resource via container_name:port
