### ISSUE TITLE
[Feature Request] Slack notification frequency

### ISSUE THREAD

**Issue by kzaoaai** [henrywhitaker3/Speedtest-Tracker#179]
Hello,

It would be nice to be able to limit the slack notifications per day. Or maybe to just send the summary of the day's averages.

**Comment by henrywhitaker3** [comment]
Try the `dev` tag mate

**Comment by kzaoaai** [comment]
I can't find anything regarding setting the frequency of the notifications. Can you please point me in the right direction?

**Comment by henrywhitaker3** [comment]
So in the settings drop-down there's a panel for notification settings. Click on edit and in the pop up you can enable/disable notifications for every speedtest, and enable a daily overview notification. In the next week or so I'll be adding notifications when a speedtest drops below a certain level as well

**Comment by henrywhitaker3** [comment]
![IMG_20200809_105816.jpg](https://user-images.githubusercontent.com/36062479/89729602-412ce200-da2f-11ea-8a35-087148232ce6.jpg)

**Comment by kzaoaai** [comment]
dohh looked everywhere except in the webgui. Thanks and good news about the conditional notifications.
