### ISSUE TITLE
[BUG] After restarting docker, multiple speed tests are taken in a row

### ISSUE THREAD

**Issue by JesseyWhite** [henrywhitaker3/Speedtest-Tracker#192]
**Describe the bug**
When I restart the docker image, many speed tests are done in a row back to back. 

**To Reproduce**
1. run a speedtest
2. restart docker

**Expected behavior**
There should only be one test taken as soon as the program is running or when the cron job is scheduled.

**Screenshots**
https://i.imgur.com/E21uch2.png
https://i.imgur.com/UyG0wI6.png

**Context**
 - OS: Docker, unraid
 - Speedtest-Tracker Version: 1.7.8:Dev

**Comment by henrywhitaker3** [comment]
Hmm, are you sure there are not loads of queued speedtests that are being run through? 

Could you put the contents of `/config/log/speedtest/queue.log`  in a pastebin please

**Comment by JesseyWhite** [comment]
[queue.log](https://github.com/henrywhitaker3/Speedtest-Tracker/files/4958112/queue.log)
Here is the log. The file was too large for Pastebin.

I noticed a lot of telegram errors, I do not use telegram so I'm unsure what that is about.

**Comment by henrywhitaker3** [comment]
Yeah have just fixed the telegram errors bit. Having looked at the queue/log, it does look like a bunch of speedtests got queued and they still hadn't run after restarting the container, so were run when you restarted. A speedtest doesn't run when the container first starts, so I can't think of any other reason for this happening.

Can you try pulling in the `dev` image again, then creating a new container with a fresh `/config` and see if you run into the same issues?

**Comment by JesseyWhite** [comment]
I think that the queue should be purged every time the container restarts. running the tests back to back like this messes up the data.

I have changed the config file as you have asked. so far, no problems related to this bug report.

**Comment by henrywhitaker3** [comment]
New image building now that clears old jobs from the queue when the container starts
