### ISSUE TITLE
[BUG] Docker - Graphs are melting?

### ISSUE THREAD

**Issue by ctc084** [henrywhitaker3/Speedtest-Tracker#198]
Hello,

I noticed sometime Tuesday that the graphs have apparently become bugged. I know the heat right now is a little much...but I digress. Attached is a video I took of the issue using Fedora 32 and Firefox (x64) 78.0.2. I am running this as a docker container on my unraid server.

[Google Drive Link to video - https://drive.google.com/file/d/1oNPVHy8mNZFbySH1k-G5vY9zQu8Vobvy/view?usp=sharing](https://drive.google.com/file/d/1oNPVHy8mNZFbySH1k-G5vY9zQu8Vobvy/view?usp=sharing)

**Comment by henrywhitaker3** [comment]
That's...really weird. Is it happening consistently? Which version of speedtest-tracker is running? (At the bottom of the page, but can't quite make it out in the video)

**Comment by ctc084** [comment]
1.7.8

Yes, it's consistent. I'm not however certain when exactly this began to occur, I usually let the tracker just start when the array does and let it roll.

**Comment by henrywhitaker3** [comment]
I'm trying to replicate this but struggling to. I'll set up a fedora vm to see but can't see it being that different from pop os with firefox.

**Comment by ctc084** [comment]
Hmmm...I purged the docker container and re-added it and with no data it still has the visual bug. It also seemingly overwhelmed Firefox and crashed the tab.

I believe this is something funky with Mozilla, I have zero issues with graph displays in Chromium.

**Comment by henrywhitaker3** [comment]
Yeah I still haven't een able to replicate this and can't see any issue on the chartjs repo for anything similar. Going to close this issue as there is not much else I can do for this
