### ISSUE TITLE
[BUG] Crontab not setting

### ISSUE THREAD

**Issue by macbean101** [henrywhitaker3/Speedtest-Tracker#212]
Under schedule, i am defining my cron timing as 10,40  * * * *  (10 and 40 minutes after the hour)

But when I use access the image cronjob, i have this:
* * * * * php /config/www/artisan schedule:run >> /config/log/speedtest/cron.logroot@70952c9bfa60:/# exit

I tried to change the cronjob but it was overwritten by the application.

Docker
Speedtest Tracker Version: 1.7.1

**Comment by henrywhitaker3** [comment]
Yeah so the docker user's Cron job should be `* * * * *`, this calls the `php artisan schedule:run` command. This command then checks if your Cron expression (stored in the database, not as an actual crontab entry) matches the current time and either runs a speedtest or does nothing. More info [here](https://laravel.com/docs/7.x/scheduling).

**Comment by macbean101** [comment]
Ah, so a misunderstanding on my part.  

I thought this was my issue because after restarting docker, the speedtest runs <successfully it seems) every 30-40 seconds (that should have been a clue I guess) and then quits until i restart it again

**Comment by henrywhitaker3** [comment]
Try switching to the `dev` image, it seems like there may be a backlog of queued tests that are being run. The Dev image clears this queue when the container starts

**Comment by macbean101** [comment]
That didn't help right away but I used the new option of 'reset speedtests' and now it seems to be acting as expected.  so far at least.

**Comment by henrywhitaker3** [comment]
Ah in that case it may have just been retrying all the failed tests again and again. Although, crontab issue has been cleared up so closing this issue now, feel free to open a new issue or comment back on this one if it starts doing tests every 40 seconds again
