### ISSUE TITLE
[BUG] Docker compose logging issue

### ISSUE THREAD

**Issue by b0red** [henrywhitaker3/Speedtest-Tracker#214]
**Describe the bug**
When i try to start the contianer from docker-compose.yml (from [here](https://hub.docker.com/r/henrywhitaker3/speedtest-tracker))
```
`speedtest:
	container_name: speedtest
	image: henrywhitaker3/speedtest-tracker:dev
	ports:
		- 8765:80
	volumes:
		- ~/docker/speedtest/data:/config
	environment:
		- TZ=${TZ}
		- PGID=${PGID}
		- PUID=${PUID}
		- BASE_PATH=/speedtest
		- OOKLA_EULA_GDPR=true
	logging:
		driver: json-file
		options:
			max-file: 10
			max-size: 200k
	restart: unless-stopped`
```
I keep getting this error: 
`ERROR: for speedtest  Cannot create container for service speedtest: json: cannot unmarshal number into Go struct field LogConfig.Config of type string`

But if I just run the docker create 
```
`docker create \
      --name=speedtest \
      -p 8765:80 \
      -v ~/docker/speedtest/config \
      #-e SLACK_WEBHOOK=webhook `#optional` \
      #-e PUID=uid `#optional` \
      #-e PGID=gid `#optional` \
      -e OOKLA_EULA_GDPR=true \
      --restart unless-stopped \
      henrywhitaker3/speedtest-tracker`
```
it works flawlessly. But no logging?

**To Reproduce**

1. create and run a docker-compose.yml file
2. watch the error

or

1. run the docker create file
2. docker run speedtest
3. watch it run

**Expected behavior**
I'd expect a functioning page with speedtest results...

**Screenshots**

**Context**
 - OS : Ubuntu 20.04
- Docker version 19.03.6, build 369ce74a3c
- docker-compose version 1.25.0, build unknown

 - Speedtest-Tracker Version: Latest(?)

**Additional context**

**Comment by christronyxyocum** [comment]
You need to quote the values, like the Docker documentation shows:

```
logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
```

This allows me to recreate the container without any issues.

**Comment by christronyxyocum** [comment]
Looks like @henrywhitaker3 updated the README to reflect my statement regarding the quotes being required for the logging values so this can probably be closed.

**Comment by henrywhitaker3** [comment]
Just seen he's thumbsed up your reply, so will close it
