### ISSUE TITLE
[BUG] Not working in Docker on Unraid

### ISSUE THREAD

**Issue by AtomicLight** [henrywhitaker3/Speedtest-Tracker#220]
Was working great until I took the update today, now there is no webui (never loads) and the log is error filled (attached)

Not sure if it's an Unraid specific issue or not.

**Comment by henrywhitaker3** [comment]
Can't see where you have put the logs. Could you post them again and let me know if you are on `dev` or `latest`

**Comment by henrywhitaker3** [comment]
If it was something along the lines of `include(/config/www/vendor/composer/../ramsey/uuid/src/Lazy/LazyUuidFromString.php`, then this isue has now been and you can now update the container to fix it.

**Comment by twistedsanity** [comment]
Just to confirm also using on unraid, mine stop testing and the manual 'test again' button also did not work. I have updated moments ago and all functionality has returned. Thanks.

**Comment by AtomicLight** [comment]
Sorry for not including the logs. I just pulled down the latest build and still not able to start it. NOW I have attached the logs.
[logs.txt](https://github.com/henrywhitaker3/Speedtest-Tracker/files/5016315/logs.txt)

**Comment by henrywhitaker3** [comment]
Hmm something messed up with your database somehow. If you make a copy of it locally then delete it from the volume and restart the ocntainer

**Comment by twistedsanity** [comment]
@AtomicLight Sorry to butt in, but if you don't mind losing the history have you tried deleting associated files from your persistent storage for this container as that looks like a database corruption. For you reference my files are stored in '/mnt/user/appdata/speedtest-tracker'

**Comment by AtomicLight** [comment]
Thanks All. I nuked it and was still having the issue. Then realized that I did not assign a WebUI port (Duuuuuuh)
 I did that now and can see the UI and run a test. I did back up my data prior to this and I am trying to restore it, but that does to seem to want to restore. Maybe I'll avoid that since maybe that is where the corruption lies?

**Comment by henrywhitaker3** [comment]
Nice one. When you say you did the restore but it didn't work, you didn't try to restore multiple times right? Otherwise you may have duplicated entries however many times you tried to restore.

Glad it's all sorted. I'm going to close the issue but feel free to comment back and it can be re-open if needed

**Comment by AtomicLight** [comment]
Yea, I think I ended up w/ multiple entries.I nuked the dbase and re-imported (once!) and back on track. Thanks again.
