### ISSUE TITLE
[Feature Request] Conditional Notification

### ISSUE THREAD

**Issue by Kingfapa** [henrywhitaker3/Speedtest-Tracker#238]
**Describe the feature**
I want to be able to configure the notifications with certain conditions so I only get notified when I want to.
Example:
I want to be notified when my internet speed is lower then a specified amount.
I want to be notified when my internet speed is percentage lower than average.

**Additional context**
I am using Speedtracker to track my internet speed and I have been having issues with my speed throttling. So I want keep track of this so I can fix it immediently.

**Comment by henrywhitaker3** [comment]
Yeah these sound like good features, on the to-do list

**Comment by henrywhitaker3** [comment]
Closing as merged into master
