### ISSUE TITLE
[Feature Request] Blacklist Hosts

### ISSUE THREAD

**Issue by JesseyWhite** [henrywhitaker3/Speedtest-Tracker#244]
**Describe the feature**
I know there is a way to whitelist server hosts, but can there be a way to blacklist a few servers?

I use the default settings for the speedtests, but I found out that one or two servers that get selected have a 3x the ping, making an average 20ms ping to 60ms. I wish to remove all results from that host and never use them in the future. 

Please note that I realize that there is a way to go about fixing my issue, but is just a feature request, not a cry for help.

**Comment by henrywhitaker3** [comment]
So this uses Ookla's speedtest cli to work, the manpage of that is:

```
Version: speedtest 1.0.0.2

Usage: speedtest [<options>]
  -h, --help                        Print usage information
  -V, --version                     Print version number
  -L, --servers                     List nearest servers
  -s, --server-id=#                 Specify a server from the server list using its id
  -I, --interface=ARG               Attempt to bind to the specified interface when connecting to servers
  -i, --ip=ARG                      Attempt to bind to the specified IP address when connecting to servers
  -o, --host=ARG                    Specify a server, from the server list, using its host's fully qualified domain name
  -p, --progress=yes|no             Enable or disable progress bar (Note: only available for 'human-readable'
                                    or 'json' and defaults to yes when interactive)  -P, --precision=#                 Number of decimals to use (0-8, default=2)
  -f, --format=ARG                  Output format (see below for valid formats)
  -u, --unit[=ARG]                  Output unit for displaying speeds (Note: this is only applicable
                                    for ‘human-readable’ output format and the default unit is Mbps)
  -a                                Shortcut for [-u auto-decimal-bits]
  -A                                Shortcut for [-u auto-decimal-bytes]
  -b                                Shortcut for [-u auto-binary-bits]
  -B                                Shortcut for [-u auto-binary-bytes]
      --selection-details           Show server selection details
      --ca-certificate=ARG          CA Certificate bundle path
  -v                                Logging verbosity. Specify multiple times for higher verbosity
      --output-header               Show output header for CSV and TSV formats

 Valid output formats: human-readable (default), csv, tsv, json, jsonl, json-pretty
 Machine readable formats (csv, tsv, json, jsonl, json-pretty) use bytes as the unit of measure with max precision

 Valid units for [-u] flag:
   Decimal prefix, bits per second:  bps, kbps, Mbps, Gbps
   Decimal prefix, bytes per second: B/s, kB/s, MB/s, GB/s
   Binary prefix, bits per second:   kibps, Mibps, Gibps
   Binary prefix, bytes per second:  kiB/s, MiB/s, GiB/s
   Auto-scaled prefix: auto-binary-bits, auto-binary-bytes, auto-decimal-bits, auto-decimal-bytes
```

Unless I'm missing something, there isn't an option to blacklist servers. The only way I could think of doing this would be running the test, if the server id is blacklisted, run the test again, repeat. However, I'm hesitant with this as it could infinitely loop if the automatically selected server is blacklisted each time, which would then stop some notifications being sent as well as blocking the scheduled tests from running.

If you can think of a better way, then I'm all ears, but I think you may just have to pick a handful of servers you like the results of and pop them in the settings.

**Comment by JesseyWhite** [comment]
You just nailed everything I was thinking and my problem. I just wanted to know if it was possible or if you knew something I didn't.

If you don't think there is a good way to go about this, then we can go ahead and close this request.

**Comment by henrywhitaker3** [comment]
I'll close the issue, but will have a think over the next few days on how this could be implemented without locking up the container. I'll re-open if I think of anything
