### ISSUE TITLE
[BUG] CSV and JSON backup data don't match

### ISSUE THREAD

**Issue by JesseyWhite** [henrywhitaker3/Speedtest-Tracker#247]
**Describe the bug**
There are more data points in the JSON backup file than the CSV file.

JSON data points:
id, ping, download, upload, created_at, updated_at, server_id, server_name, server_host, URL, scheduled, failed

CSV data points:
id, ping, download, upload, created_at, updated_at

**To Reproduce**
1. Download CSV Backup
2. Download JSON Backup
3. Open both files
4. Notice the difference

**Expected behavior**
Both backup files should have the exact same data

**Screenshots**
JSON data [imgur.com/wS7UzrI.png](https://i.imgur.com/wS7UzrI.png)
CSV data [imgur.com/MNNe9gj.png](https://i.imgur.com/MNNe9gj.png)

**Context**
 - OS: Unraid Docker
 - Speedtest-Tracker Version: 1.17.13

**Comment by henrywhitaker3** [comment]
Yeah I haven't been updating the CSV as I've added new fields. Have just had a look, and have updated some stuff, but there won't be any support for backing up `server_name` as these results get returned with commas in them which obviously breaks the CSV formatting.

I'll work on a function that gets called on container start to clean this up but will push the updates leaving it out for now.

**Comment by JesseyWhite** [comment]
#248 

Fixed this error with my pull request

**Comment by henrywhitaker3** [comment]
Scrap what I just said, I'm just going to clear the commas out when the CSV is generated and include all the fields

**Comment by henrywhitaker3** [comment]
Right, change shave been merged into `dev` on github in #249. It's pretty late so it won't be until tomorrow until I update the docker image

**Comment by JesseyWhite** [comment]
That's fine, I used my own changes to get what I wanted the CSV backup for. I'll just roll with that until the docker updates. Thanks for the speedy updates!

**Comment by henrywhitaker3** [comment]
Closing as merged into master
