### ISSUE TITLE
[Feature Request] Minumum for download and upload

### ISSUE THREAD

**Issue by jterpstra1** [henrywhitaker3/Speedtest-Tracker#264]
**Describe the feature**
An extra value for the lowest recorded upload and download speed.
You can see the lowest value in the graph but a lowest value above the averge speed would be nice

**Comment by jterpstra1** [comment]
I would like this:

![image](https://user-images.githubusercontent.com/49212524/91146559-594f6300-e6b7-11ea-98f0-83bf5b8685c4.png)

and then for each one so a minimum value which contains the lowest recorded speed

**Comment by henrywhitaker3** [comment]
Sorry this took so long. Just merged into the `dev` tag

**Comment by jterpstra1** [comment]
Thanks! Just switched to dev build, it's great! 
![image](https://user-images.githubusercontent.com/49212524/93020438-4f958d00-f5dd-11ea-9d7f-b4b3151afbd9.png)
