### ISSUE TITLE
[Feature Request] Show failed tests on graph

### ISSUE THREAD

**Issue by ChawiBiker** [henrywhitaker3/Speedtest-Tracker#285]
**Describe the bug**
The Download/Upload window does not show a gap when a speedtest fails - for example because internet is down.
You can see this on the two attached pictures. Several hours and test are lying between both points but there is no gap.

**Expected behavior**
 I would like to see a break there for the length of the failing tests. For example dropping to the bottom and changing the line to red for this period.

**Screenshots**
<img width="106" alt="Bildschirmfoto 2020-08-28 um 21 11 12" src="https://user-images.githubusercontent.com/60240729/91606804-10c3ce00-e973-11ea-9a68-1ffb0cb66aa2.png">
<img width="138" alt="Bildschirmfoto 2020-08-28 um 21 11 21" src="https://user-images.githubusercontent.com/60240729/91606801-0f92a100-e973-11ea-8175-8e322272bbe7.png">

**Context**
 - OS: Running in Docker on Synology NAS version 1.7.15
 - Speedtest-Tracker Version:

**Comment by henrywhitaker3** [comment]
Right, if you pull the latest `dev` tag I've added a setting to show/hide failed tests in the graphs. It defaults to on, but if you want to toggle it off it's in settings -> graph settings.

**Comment by henrywhitaker3** [comment]
Closing as merged into master
