### ISSUE TITLE
[BUG] speedtest needs executable bit

### ISSUE THREAD

**Issue by dylanmtaylor** [henrywhitaker3/Speedtest-Tracker#296]
It is sometimes possible (I encountered this, not 100% sure how to reproduce) for the speedtest binary to not have executable permissions. chmod +x from within the container fixes this. I was thinking that a good fix would be to run something along the lines of 
        shell_exec('chmod +x ' . app_path() . '/Bin/speedtest');
before the initial EULA accept command to fix it.

As a brief test, this should work:
```
➜  Speedtest-Tracker git:(master) chmod -x ~/.config/appdata/speedtest/www/app/Bin/speedtest
➜  Speedtest-Tracker git:(master) docker restart speedtest
speedtest
➜  Speedtest-Tracker git:(master) docker exec -it speedtest bash     
root@Dylan-Precision-5540:/# chmod +x /config/www/app/Bin/speedtest 
root@Dylan-Precision-5540:/# exit
➜  Speedtest-Tracker git:(master) ls -lah ~/.config/appdata/speedtest/www/app/Bin             
total 2.2M
drwxrwxr-x  2 dylan dylan 4.0K Aug 26 20:02 .
drwxrwxr-x 15 dylan dylan 4.0K Aug 26 20:02 ..
-rw-rw-r--  1 dylan dylan   10 Sep  3 17:08 .gitignore
-rwxrwxr-x  1 dylan dylan 2.2M Aug 26 20:02 speedtest
```

**Comment by dylanmtaylor** [comment]
Looks like a great solution, better than I came up with

**Comment by henrywhitaker3** [comment]
Closing as merged into master
