### ISSUE TITLE
[BUG] Failure rate is not quite in sync with local time.

### ISSUE THREAD

**Issue by JesseyWhite** [henrywhitaker3/Speedtest-Tracker#320]
**Describe the bug**
I've noticed that the failure rate bar graph is not the same time as local time. It is hours behind, almost an entire day, and I think that it sectioning off the time from another time zone.

**To Reproduce**
1. have speed test data, about 3 days worth
2. do a speed test a little after midnight
3. notice how the bars are not at the same time as your own
4. if you do not notice, try changing the local machine's timezone

**Expected behavior**
The bars should be in sync with the local time

**Screenshots**
look at the picture below, notice the local date and the date on the bar graph 
[i.imgur.com/lup5vJA.png](https://i.imgur.com/lup5vJA.png)

The container time is correct
[i.imgur.com/HuzFJWV.png](https://i.imgur.com/HuzFJWV.png)

**Context**
 - OS: Unraid
 - Speedtest-Tracker Version: 1.9.8

**Comment by wbernier8** [comment]
I'm still having this same issue with v1.12.0 on Ubuntu
