### ISSUE TITLE
[Feature Request] Setup Custom DNS Server 

### ISSUE THREAD

**Issue by corasaniti** [henrywhitaker3/Speedtest-Tracker#327]
**Describe the feature**
It would be nice to be able to set a custom DNS server different from the system one. 
I use a custom DNS but for the test I would like to use the Google DNS
Thank you

**Comment by henrywhitaker3** [comment]
You should be able to override DNS resolver when creating the container or in your compose file.

If you're using a manual install, can you give me a bit more info? What's the need for a different DNS server?

**Comment by corasaniti** [comment]
I Henry thanks for your answer.

Do you mean to create the container starting from the DockerFile? I'm not very skilled and I'm not familiar with Dockerfille commands. Could you help me?

I use a Raspberry with Pihole as DNS server that logs all requests I would like to avoid logging during the speedtest, setting the Google DNS 8.8.8.8

Thank you

**Comment by corasaniti** [comment]
Hi Henry,

I solved it by creating the container as follows

docker create \
      --name=speedtest \
      --hostname speedtest \
      --dns 8.8.8.8 \
      -p 8080:80 \
      -v /home/corpie/docker-containers/speedtest-tracker/config:/config \
      -e OOKLA_EULA_GDPR=true \
      --restart unless-stopped \
      henrywhitaker3/speedtest-tracker

Thanks

**Comment by corasaniti** [comment]
I solved it by creating the container as follows, adding --dns 8.8.8.8 parameter
