### ISSUE TITLE
[BUG] Firefox: Upload/Download and ping graphs increase in size

### ISSUE THREAD

**Issue by PPHyperion** [henrywhitaker3/Speedtest-Tracker#336]
After opening the WebUI in Firefox the upload/download graph and the ping graph increase in height. The growing does not seem to stop. The width of the graphs does not change. The failure graph is not affected. Removing and readding the graphs does not resolve the issue. When using chrome, the problem does not appear.

1. Go to the WebUI
2. See error

**Screenshots**
[screenshot (imgur)](https://imgur.com/a/SLz3wAn)

**Context**
 - OS: Speedtest-Tracker runs as a Docker Container and the Firefox client used is version 81.0.1 (64-bit) running on Arch Linux
 - Speedtest-Tracker Version: [1.9.6]

**Comment by PPHyperion** [comment]
Just tried the demo that's in the readme.md and there the bug also appears.

**Comment by henrywhitaker3** [comment]
Seems the same as #198. I use Ubuntu 20.04 and Firefox and was unable to replicate the issue

**Comment by LordPistachio** [comment]
I am experiencing the same issue. Running in a docker container with Firefox.
Not particularly useful information, but here it is anyway,

All Firefox extensions disabled.

Ubuntu 20.04.1
Docker 19.03.13
Docker Compose 1.27.4
Firefox 83.0

**Comment by simonholl** [comment]
I am experiencing the same issue. Running in a docker container with Firefox.
Not particularly useful information, but here it is anyway,

All Firefox extensions disabled.

Ubuntu 20.04.1
Docker 19.03.13
Docker Compose 1.27.4
Firefox 83.0

**Comment by henrywhitaker3** [comment]
As I said in another issue, I'm planning to re-write the whole UI from scratch so going to close this issue off
