### ISSUE TITLE
[Feature Request] Setting to allow auto-pruning of laravel.log file

### ISSUE THREAD

**Issue by Tharic99** [henrywhitaker3/Speedtest-Tracker#338]
**Describe the feature**
I've been running speedtest for a few months now and I've noticed that in my docker container appdate the 
/www/storage/logs/laravel.log file is 4gb in size. I'm assuming this is somehow related to my speedtest logs themselves, so I'd like the ability to configure a setting to prune tests over X days. Sure, history is great, but do I need speedtests over 90 days? over 30 days? over 365 days? Make it configurable so a user can set what the X days are for themselves.

Hopefully that's what the laravel.log file is doing. Otherwise, this may not really be a Feature Request.

**Comment by henrywhitaker3** [comment]
Yeah I have had that on the to-do list for ages but haven't got round to it yet. Will include that in the next update (next week hopefully).

Feel free to delete that file though, it's not where the speedtests are stored it's just debug logs.

**Comment by Tharic99** [comment]
Awesome. Thanks. Will that file re-create itself?

**Comment by henrywhitaker3** [comment]
Yeah it should do

**Comment by henrywhitaker3** [comment]
This is now in the latest `dev` tag now mate. Give it a go
