### ISSUE TITLE
Docker for raspberry pi 4

### ISSUE THREAD

**Issue by shlagwuk** [henrywhitaker3/Speedtest-Tracker#34]
Hey! Your app seems very cool! Is it possible to have a raspberry pi 4 docker image ?
I don’t know if it’s a lot of job or not ;-)
Best regards,

Simon

**Comment by henrywhitaker3** [comment]
Yeah I'll get an image that works with raspberry pi's out. Will be a bit busy for the next few weeks, so there won't be a build available for a while.

**Comment by corasaniti** [comment]
I agree with @shlagwuk , it would be very nice to have a docker image that you can use with Raspberry4
We look forward with interest.
Thank you

**Comment by rubenix** [comment]
Any update on the Rpi 4 docker image?
Thanks!

**Comment by henrywhitaker3** [comment]
Yeah should've updated this issue, so docker hub doesn't support automated builds for arm devices. 

When I'm home I'll write a quick script that will build it locally for arm devices and add it to the wiki (will also link it here)

**Comment by rubenix** [comment]
whoa that sounds nice!! you're fast man!!

**Comment by henrywhitaker3** [comment]
Gonna be tomorrow now mate, sorry

**Comment by jackitsdotcom** [comment]
This would be fantastic. Tried to do the manual install and while `php artisan speedtest:run` works, I can't find the web interface served anywhere. Thankyou.

**Comment by henrywhitaker3** [comment]
Right, sorry it's late and has taken so long since this issue was created, but here is a script that will build an image that works on a Pi (although it takes a while to build/copy files, but that's a pi limitation)

[https://gist.github.com/henrywhitaker3/c6663036a0ae4355843c34cb84859d97](https://gist.github.com/henrywhitaker3/c6663036a0ae4355843c34cb84859d97)

@shlagwuk @rubenix @jackitsdotcom

**Comment by gcvasconcelos** [comment]
This solution worked for my raspberry pi 3, but after a day, i'm getting this error:
> To accept the message please run speedtest interactively or use the following: speedtest --accept-gdpr

When I try to run the command above, I get this error: 
> speedtest: error: unrecognized arguments: --accept-gdpr

**Comment by corasaniti** [comment]
@gcvasconcelos 
make sure you create the container by passing the OOKLA_EULA_GDPR parameter set to true

docker create \
       --name = speedtest \
       -p 8765: 80 \
       -v / path / to / data: / config \
       -e OOKLA_EULA_GDPR = true \
       --restart unless-stopped \
       henrywhitaker3 / speedtest-tracker

Ciao

**Comment by rubenixnagios** [comment]
working flawlessly on rpi 4 with script image generator! Thanks so much @henrywhitaker3

**Comment by henrywhitaker3** [comment]
@gcvasconcelos like the other corsaniti said, did you set the `OOKLA_EULA_GDPR` env car to true?

If you did, can you navigate to the Speedtest-Tracker dir (`/config/www` in container) and run `php artisan speedtest:eula` to accept the eula

**Comment by shlagwuk** [comment]
do you know how can I prevent docker-compose from pulling a new image anytime I run "docker-compose pull" ? It seems I have to run the script each time I update my other dockers.

**Comment by henrywhitaker3** [comment]
The script was more of a quick fix, I'm going to be working on it this weekend to try to add `arm-latest` and `arm-dev` tags to dockerhub

**Comment by gbh420** [comment]
Till there is an 'official' armhf I found this on dockerhub... https://hub.docker.com/r/seltun/speedtest-tracker-armhf.  Ive got it on RP4 running fine apart from known issues.

**Comment by hferreira23** [comment]
@henrywhitaker3 github workflows allows using docker buildx to build images in multiple arch and push them to Docker hub.

50-speedtest will have to be updated to fetch the right arch binary of speedtest

Happy to help with some PRs in the weekend if you want

**Comment by henrywhitaker3** [comment]
Thanks for the offer mate, but want to keep using docker hub automated builds for now. 

Images are now on docker hub for arm: `latest-arm` and `dev-arm`
