### ISSUE TITLE
[Feature Request] Multiple Agents

### ISSUE THREAD

**Issue by StevenChorkley** [henrywhitaker3/Speedtest-Tracker#35]
Hi, 

Would it be possible to set this up to use 2x agents? 
In my use case, nginx reverse-proxy is hosted on a hosted dedi server whilst my services are hosted at home. 

I'd like the speedtest tracker to work for both connections if possible?

**Comment by henrywhitaker3** [comment]
Not going to have the time to work on this for the next few weeks, but sounds like a good feature. If you feel like working on it, feel free to submit a PR, otherwise you might have to wait a bit for it.

**Comment by henrywhitaker3** [comment]
Not looking like I'm going to have the time to work on this, so going to close the issue
