### ISSUE TITLE
[Feature Request] Allow for blacklisting/whitelisting of speedtest servers from All Tests section

### ISSUE THREAD

**Issue by altafkassam** [henrywhitaker3/Speedtest-Tracker#354]
Some Speedtest servers return inconsistent results. It would be convenient to allow for the blacklisting or whitelisting of Speedtest servers from the 'All Tests' section.

**Comment by henrywhitaker3** [comment]
Not sure I understand what that would achieve? Would be far easier to go into the settings and supply the server ID of speedtest servers you want to run tests against. You can just enter 1 ID, or enter multiple comma-separated and it will pick out of those randomly

**Comment by henrywhitaker3** [comment]
Am going to close this as you can't blacklist a server with the Ookla's cli and whitelisting functionality already exists
