### ISSUE TITLE
[BUG] Unable to deploy in kubernetes

### ISSUE THREAD

**Issue by bluej007** [henrywhitaker3/Speedtest-Tracker#359]
**Describe the bug**
When deploying in a kubernetes cluster, the logs show the below errors after **[cont-init.d] 50-speedtest: executing...** and each time I attempt to run a test. I've tried the latest and dev branch.

[error] Trying to get interface information on non-initialized socket.
[error] Configuration - Couldn't resolve host name (HostNotFoundException)
[error] Configuration - Cannot retrieve configuration document (0)
[error] ConfigurationError - Could not retrieve or read configuration (Configuration)
[error] ConfigurationError - Could not retrieve or read configuration (Configuration)
[error] Configuration - Could not retrieve or read configuration (ConfigurationError)

**Expected behavior**
These errors do not appear when deploying straight from Docker.

**Context**
 - OS: Ubuntu 18.04
 - Speedtest-Tracker Version: 1.9.6

**Comment by henrywhitaker3** [comment]
What happens if you get a shell and run `HOME=/config && /config/www/app/Bin/speedtest`?

**Comment by bluej007** [comment]
> What happens if you get a shell and run `HOME=/config && /config/www/app/Bin/speedtest`?

Same errors

**Comment by henrywhitaker3** [comment]
Ngl mate, have never used kubernetes so not too sure how to help with this. The guy from issue #183 got it working I think, so might be able to help you out

**Comment by bluej007** [comment]
I read thru issue #183 and it was a great help. In the end, the issue is k8s has a default ndots value of 5. Once I set the ndots value to 1 for this container, it worked great.
