### ISSUE TITLE
[BUG] Black Screen after some uptime

### ISSUE THREAD

**Issue by ChawiBiker** [henrywhitaker3/Speedtest-Tracker#368]
**Describe the bug**
The program runs fine and pushes the tests to me via Telegram but after several hours of uptime I can’t access the webpage anymore. Just a black screen is loading. In order to gain access to the web interface again I have to restart the container. After that it works again for a few hours.

**Screenshots**
![D2D26F67-DB78-4D30-B1FD-07720918D0B7](https://user-images.githubusercontent.com/60240729/98239512-5c44ba80-1f68-11eb-8e46-2109dee260e1.jpeg)

**Context**
 - Docker on Synology
 - I have the problem on stable and dev

**Additional context**
The system runs fine and pushes the tests via telegram to me.

**Comment by henrywhitaker3** [comment]
Yeah that's pretty weird. I have a container with a over a month uptime that's still working fine. There anything in the browser console?

**Comment by ChawiBiker** [comment]
When I load the page the "network" console of the developer tools in chrome just loads this.
I just hid the first line with my ip.

<img width="318" alt="Bildschirmfoto 2020-11-08 um 12 07 36" src="https://user-images.githubusercontent.com/60240729/98463397-48dd5d80-21bb-11eb-8c5a-6cf6d50e03c0.png">

**Comment by henrywhitaker3** [comment]
They're not really that useful. Is there any network logs that failed or are in red?

Are there any errors in the console?

Is there anything in the docker or laravel logs?

**Comment by Guillaume-iov42** [comment]
Hello - I have a similar issue on docker container in a Synology NAS, my speedtest-tracker usually dies after a few hours (sometimes one day, sometimes less) and gives me a black page.
The only relevant thing I can find is in the nginx log in the config folder (`/config/log/nginx/error.log`):

```
crit] 454#454: *12562 open() "/var/lib/nginx/tmp/fastcgi/5/01/0000000015" failed (13: Permission denied) while reading upstream, client: 172.17.0.1, server: _, request: "GET /files/js/app.js?v=1-9-6 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "<myhost>", referrer: "https://<myhost>/"
```
(Host replaced with `<myhost>`) for privacy.

An entry likes that is generated every time I try to access it.
When I restart the docker container, it starts working again.

**Comment by juliangopp** [comment]
Happy new year Henry!
Same issue here. On a QNAP NAS, using the "latest-arm" build.
After several hours, the web frontent isn't loading anymore. Restarting the container doesn't help. Recreating the container solves the problem.
Authentication is turned off (AUTH -> not set to true). I'm accessing the webfrontent from my internal network only.
The jobs / speedtests are still executed. I just can not access the results through the frontend.

In the nginx log I found:
2021/01/08 08:14:06 [crit] 425#425: *258 open() "/var/lib/nginx/tmp/fastcgi/9/00/0000000009" failed (13: Permission denied) while reading upstream, client: 192.168.0.58, server: _, request: "GET /files/js/app.js?v=1-10-0 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.59", referrer: "http://192.168.0.59/"

The browser console says:
Laden fehlgeschlagen für das <script> mit der Quelle "http://192.168.0.59/files/js/app.js?v=1-10-0". 192.168.0.59:39:1
(translated in english: Loading failed for the <script> with the source "http://192...."

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.0.59/files/js/popper.min.js
Source-Map-Adresse: popper.min.js.map

the Browser console help points to: https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

However I can access http://192.168.0.59/files/js/popper.min.js/ and this shows me some text starting with  /* Copyright (C) Federico Zivolo 2017....

any idea?

**Comment by henrywhitaker3** [comment]
Yeah have seen this myself. I'm gonna close this issue though as I'm planning on re-writing the UI from scratch so should fix this anyway
