### ISSUE TITLE
[BUG] Unable to 'Test Again'

### ISSUE THREAD

**Issue by zachbunyard** [henrywhitaker3/Speedtest-Tracker#370]
**Describe the bug**
Speedtests executed by clicking 'Test Again' button fail with error in laravel.log:

```
[2020-11-06 21:27:15] local.ERROR: Failed to parse speedtest JSON  
[2020-11-06 21:27:15] local.ERROR:   
```

**To Reproduce**
1. Go to speedtest tracker web page
2. Click on 'Test Again'
3. UI will show failed test
4. See error in laravel.log file

**Expected behavior**
The speedtest completes successfully

**Context**
 - OS: Ubuntu 20.04
 - Speedtest-Tracker Version: 1.9.6
 - NodeJS Version: 10.23.0
 - PHP Version: 7.4.12 (FPM)

**Additional context**
This issue occurs regardless of what servers are listed in Settings > Server
Speedtest completes successfully when running the command `php artisan speedtest:run`

**Comment by henrywhitaker3** [comment]
Not really sure why you'd be getting differences there then, `speedtest:run` calls the exact same code...

There anything in the docker logs when that happens?

**Comment by zachbunyard** [comment]
I run a manual setup.  I don't use docker.  I don't see anything in the Nginx logs though.

**Comment by henrywhitaker3** [comment]
Okay, a bit of manual testing here but can you add `Log::info($output);` to line 29 of app/Helpers/SpeedtestHelper.php please. That way we can see what's causing the error to be thrown

**Comment by zachbunyard** [comment]
I added that to the file, and the log output changed to now be:
```
[2020-11-09 20:21:05] local.INFO:   
[2020-11-09 20:21:05] local.ERROR: Failed to parse speedtest JSON  
[2020-11-09 20:21:05] local.ERROR:
```

If I run `php artisan speedtest:run` via command line, the error doesn't occur and a log.INFO line is present showing the full JSON results.

**Comment by henrywhitaker3** [comment]
So looks like an issue with the queue worker. There anything in the supervisor logs?

**Comment by Guruleenyc** [comment]
I am running the docker and scheduled tests or manual test no longer work. Last success test was yesterday 11/8/2020. Any resolution for this.

**Comment by henrywhitaker3** [comment]
Anything in the docker logs?

**Comment by zachbunyard** [comment]
Under /var/log/supervisor, I see 8 files named similarly to laravel-worked-02-stdout---supervisor-btefx4wc.log

Shortly after clicking 'Test again', the following appears in one of them:
```
[2020-11-09 21:15:30][2380] Processing: App\Jobs\SpeedtestJob
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
[2020-11-09 21:15:31][2380] Processed:  App\Jobs\SpeedtestJob
```

**Comment by Guruleenyc** [comment]
After restarting docker, manual test was successful. I did not see anything in docker log:
`Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 911
User gid: 911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing...
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-speedtest: executing...
Copying latest site files to config
Database file exists
Env file exists
Running database migrations
Nothing to migrate.
App key exists
JWT secret exists
Slack webhook set, updating db


Not enough arguments (missing: "webhook").


Telegram chat id and bot token unset
Base path is unset
AUTH variable not set. Disabling authentication
Disabling authentication
Clearing old jobs from queue
[cont-init.d] 50-speedtest: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.`

**Comment by henrywhitaker3** [comment]
@Guruleenyc I reckon it might have been your EULA acceptance expiring

**Comment by henrywhitaker3** [comment]
@zachbunyard I've never seen this error before. And it's hard to see what's going on without being there. I'd say maybe delete your vendor folder and composer install again? Honestly not too sure. How opposed to running docker are you?

**Comment by Guruleenyc** [comment]
> @Guruleenyc I reckon it might have been your EULA acceptance expiring

I installed the docker yesterday and accepted the EULA during install. It worked for one day...

**Comment by henrywhitaker3** [comment]
@gyoh it won't be that then. Without seeing the docker logs before the restart it's hard to tell. Just see how it goes for now, if it happens again save the docker logs before restarting

**Comment by Guruleenyc** [comment]
> @gyoh it won't be that then. Without seeing the docker logs before the restart it's hard to tell. Just see how it goes for now, if it happens again save the docker logs before restarting

Thank you for the fast reply. I'll monitor it and see what happens...

**Comment by zachbunyard** [comment]
I'm trying to run this app within an LXC container.  At ome point in time, it worked without issue.  I'm coming back to Speedtest-Tracker after not using it for some time.  I'd like to run it the same way I did before.  Another level of containerization by adding Docker to the mix is a less than appealing idea...

Is there any other information I can provide that would make tracking the cause of this issue easier?

**Comment by henrywhitaker3** [comment]
I'll try setting it up in an lxc later this week and see if I can replicate anything. No reason it shouldn't work there, it's what I used to run it before I made the docker container

**Comment by Guruleenyc** [comment]
18h later and its still working since restarting docker ;-)

**Comment by Guruleenyc** [comment]
After approx. 48hr, it is not performing any more tests. The manual test also does not update graphs. Graph is missing data for today as well.

**Comment by henrywhitaker3** [comment]
Anything in the docker logs or? browser console?

Can't remember what the default is, but it might be hiding failed tests from the graph. What have you got the schedule set to?

**Comment by Guruleenyc** [comment]
> Anything in the docker logs or? browser console?
> 
> Can't remember what the default is, but it might be hiding failed tests from the graph. What have you got the schedule set to?

My scan schedule is every 3h and my docker logs show:
`[2020-11-11 04:00:31.517] [error] Configuration - Couldn't connect to server (Network is unreachable)

[2020-11-11 04:00:31.517] [error] Configuration - Cannot retrieve configuration document (0)

[2020-11-11 04:00:31.517] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)

[2020-11-11 04:00:31.520] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)

{"type":"log","timestamp":"2020-11-11T09:00:31Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}
`

**Comment by henrywhitaker3** [comment]
Looks like something is messing up in the docker networking then

**Comment by Lynxy** [comment]
I am running into this same issue, manual install on LXC.

Pressing the "Test Again" button queues it up and takes awhile to complete like it is actually running the test.

I added the logging code mentioned by @henrywhitaker3 and this is what outputs:
```
[2020-11-14 15:23:22] local.ERROR: Failed to parse speedtest JSON
[2020-11-14 15:23:22] local.ERROR:
```

Content of `/var/log/supervisor/`:
```
[2020-11-14 15:23:22][24] Processing: App\Jobs\SpeedtestJob
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
[2020-11-14 15:23:22][24] Processed:  App\Jobs\SpeedtestJob
```

Like the OP, manually running `php artisan speedtest:run` via the command line, as well as the cron job, work fine. This is a brand new manual install barely an hour old and the "Test Again" button has never worked.

The `SpeedtestHelper::output()` function (line 96) runs the following shell command:
`HOME=/opt/Speedtest-Tracker/ && /opt/Speedtest-Tracker/app/Bin/speedtest -f json`

Manually running that command myself and it looks like there are 2 JSON responses in the output, the first one being an error that outputs immediately upon running the command. In actuality, the first JSON object is part of the error output.
```
{"type":"log","timestamp":"2020-11-14T15:37:22Z","message":"Error: [-2] Protocol error: Did not receive HELLO","level":"error"}
{"type":"result","timestamp":"2020-11-14T15:37:50Z","ping":{"jitter":3.4369999999999998,"latency":36.009999999999998},"download":{"bandwidth":31115827,"bytes":403495736,"elapsed":14275},"upload":{"bandwidth":2654726,"bytes":25711857,"elapsed":10274},"packetLoss":0,"isp":"REDACTED","interface":{"internalIp":"REDACTED","name":"eth1","macAddr":"REDACTED","isVpn":false,"externalIp":"REDACTED"},"server":{"id":1234,"name":"REDACTED","location":"REDACTED","country":"United States","host":"REDACTED","port":8080,"ip":"REDACTED"},"result":{"id":"REDACTED","url":"https://www.speedtest.net/result/c/REDACTED"}}
```

If I redirect errors with `2>/dev/null` in the console then the output looks right, just one JSON object. However, when I plug this into the code it seems to have no effect. Further debugging shows that `$output` is always empty regardless of error redirection.

I have since given up on trying to solve this as the cron job does all I need. Hope this helps someone further debug the issue.

**Comment by henrywhitaker3** [comment]
Yeah haven't had the time yet to start looking into this, have been pretty busy recently. Thanks for the debugging @Lynxy will definitely be helpful

Only thing I can't understand is why the schedule/Cron job works but the manual test doesn't, as it's just the same code running, same with running `php artisan speedtest:run` (think that's the command) Must be something to do with supervisor

**Comment by henrywhitaker3** [comment]
@Lynxy can you have a look at the queue section of [here](https://github.com/henrywhitaker3/Speedtest-Tracker/wiki/Manual-Installation) again. Have decided to go with systemd instead of figuring out why supervisor wasn't working

**Comment by mptpro** [comment]
I am having the same error message using Docker. Not sure where to begin so solve this.

`Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}
`

PS Where do you see the "Test Again" button?  I only see "Queue Speedtest" which takes quite some time before it begins the test.
