### ISSUE TITLE
[BUG] Server list is ignored

### ISSUE THREAD

**Issue by bluej007** [henrywhitaker3/Speedtest-Tracker#383]
**Describe the bug**
When I enter an IP in the server setting,  click "Test Again", and then view the test's results, it goes to the wrong server.

**Expected behavior**
For the test to run against the specified IP

**Screenshots**
Server setting:
![server](https://user-images.githubusercontent.com/53668195/98742222-aae0c300-2373-11eb-9662-e2a1af8966c2.png)

Test result:
![test](https://user-images.githubusercontent.com/53668195/98742232-af0ce080-2373-11eb-802e-e96fa7a93aa5.png)

Nslookup:
![nslookup](https://user-images.githubusercontent.com/53668195/98742236-b16f3a80-2373-11eb-856a-4d1f6fa88c98.png)

**Context**
 - OS: Docker
 - Speedtest-Tracker Version: 1.9.6

**Comment by henrywhitaker3** [comment]
You want the server ID not the IP address
