### ISSUE TITLE
[BUG] No such file or directory

### ISSUE THREAD

**Issue by A-Alhashem** [henrywhitaker3/Speedtest-Tracker#386]
**Describe the bug**
I'm on Ubuntu, did a manual installation.
I went over each step and made sure everything was working correctly.

I have tested the app from CLI using `php artisan speedtest:run`

I am using nginx reverse proxy for the subfolder for speedtest.
this is my location block:
```
location /speedtest {
        alias /home/user/Speedtest-Tracker/public;
        location ~ \.php$ {
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
                include snippets/fastcgi-php.conf;
                fastcgi_param SCRIPT_FILENAME $request_filename;
                include fastcgi_params;
        }
}
```
the `./public` directory contains the index.php.

I have also edited `.env` with the following:
```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:<some random KEY code>
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=sqlite
# Use absolute paths to the database
DB_DATABASE=/home/user/Speedtest-Tracker/database/speed.db

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=database
SESSION_DRIVER=file
SESSION_LIFETIME=120

SPEEDTEST_EMAIL=
SPEEDTEST_PASSWORD=

# Number of days you stay logged in for
REMEMBER_DAYS=30

SLACK_WEBHOOK=

TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=

BASE_PATH=/speedtest

```
as I have added the `BASE_PATH`.

When I goto "https://domain.com/speedtest" the page is white, empty.
Checking the nginx log it shows:
`/home/user/Speedtest-Tracker/public/files/js/main.css.js" failed (2: No such file or directory)`
`/home/user/Speedtest-Tracker/public/files/js/app.js" failed (2: No such file or directory)`
etc...
and several lines. I realized that I do not have a `/files/` directory, it doesn't even exist, it should be:
`/home/user/Speedtest-Tracker/public/js/app.js` without `/files/`

but what I did is just created a `/files` directory and copied everything under `/public/` directory and into the `/files/` directory so the script would catch them.

After that I went back into "https://domain.com/speedtest" and now I have a Dark Grey background with a white dot in the middle as if its trying to load the data in.

Checking the nginx log it reads:
`"/home/user/Speedtest-Tracker/public/api/settings/config" failed (2: No such file or directory)`

now the whole `/api/settings/config` doesn't even exist. I'm sure I'm missing something but I've been at it for 2days and I ran out of ideas.

**To Reproduce**
1. Went into the wiki page for manuall installation, made sure I installed all dependancies
2. git cloned speedtest-tracker, then downloaded the speedtest cli, and moved it inside as instructed.
3. cd into speedtest-tracker and performed `compose install` as well as `npm install && npm run production`
4. performed `cp .env.example .env` and edited as instructed with adding `BASE_PATH=/speedtest`
5. Accepted Ookla's EULA by running `php artisan speedtest:eula` then test ran `php artisan speedtest:run`
6. as my server is remote, I added the location block, but once I navigated to domain.com/speedtest I got errors on my nginx log

**Context**
 - OS: Ubuntu 20.04 LTS headless
 - Speedtest-Tracker Version: cloned `https://github.com/henrywhitaker3/Speedtest-Tracker.git` as of today. I couldn't find the version number.

**Extra Info**
I also use Organizr as my dashboard, alongside netdata and other apps

**Comment by henrywhitaker3** [comment]
When I get back from work later I'll send you my nginx config. The `/files/ directory shouldn't exist. There's a route that catches all requests to `/files/*` that returns the file from public folder.

Try adding a trailing slash to the URL, and it should work for base path.

The fact that the API routes don't exist means there's definitely an nginx config issue somewhere though

**Comment by A-Alhashem** [comment]
> When I get back from work later I'll send you my nginx config. The `/files/` directory shouldn't exist. There's a route that catches all requests to `/files/*` that returns the file from public folder.
> 
> Try adding a trailing slash to the URL, and it should work for base path.
> 
> The fact that the API routes don't exist means there's definitely an nginx config issue somewhere though

Thanks! I'll add the trailing slash and see what happens.

**Comment by A-Alhashem** [comment]
Tried it again, still same problem. I have also changed the nginx conf to add trailing slash and checking the logs, also edited the .env file for BASE_URL.
They're all leading me to the same problem.

I'll wait for your nginx config, I may have messed up somewhere.

**Comment by henrywhitaker3** [comment]
It will need tweaking, but on my public-facing nginx it is running:

```
location /speedtest {
    return 301 $scheme://$host/speedtest/;
}
location ^~ /speedtest/ {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app speedtest;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}
```

and in the container, it's this:

```
server {
	listen 80 default_server;

	listen 443 ssl;

	root /config/www/public;
	index index.html index.htm index.php;

	server_name _;

	client_max_body_size 0;

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		# With php5-cgi alone:
		fastcgi_pass 127.0.0.1:9000;
		# With php5-fpm:
		#fastcgi_pass unix:/var/run/php5-fpm.sock;
		fastcgi_index index.php;
		include /etc/nginx/fastcgi_params;

	}
}
```

**Comment by A-Alhashem** [comment]
I may hit my limits of my knowledge of nginx here.

the app doesn't have a dedicated port right? similar to other apps like netdata, radarr, sonarr etc..

It's mostly similar to Monitorr correct? Because I see you're using a port number 9000, but your location block is using port 80.

I'm accessing my server remotely, and I've installed Organizr's OUI bash script for my ubuntu server which came with nginx.

But from your location block, where are you calling your public index.php file ?

Should I move my Speedtest-Tracker directory to somewhere else?

Atm its sitting in my /home/ directory, and using `alias` to call my index.

**Comment by henrywhitaker3** [comment]
Yeah it the most similar to monitorr, with sonarr etc. There is a service running constantly, but with PHP there's only something running when you visit the page in the browser.

The port 9000 is to php-fpm which is what actually executes the PHP code, and this bit `try_files $uri $uri/ /index.php?$args;` is where index.php is called

**Comment by darkknight6722** [comment]
> I'm accessing my server remotely, and I've installed Organizr's OUI bash script for my ubuntu server which came with nginx.
> 
I too installed nginx with Organizr script. Try this.
```
server {
        listen 80; listen [::]:80;
	listen 443 ssl http2; listen [::]:443 ssl http2;
    
	include /etc/nginx/config/others/ssl.conf;

	server_name speedtest.example.com;
	
	root /var/www/speedtest-tracker/public;
	index index.html index.htm index.php;


	location / {
		try_files $uri $uri/ /index.php?$args;
	location ~ \.php$ {
       		fastcgi_pass unix:/run/php/php7.4-fpm.sock;
       	        include snippets/fastcgi-php.conf;
       	        fastcgi_param SCRIPT_FILENAME $request_filename;
       	        include fastcgi_params;
        	}
	}
}
```

**Comment by A-Alhashem** [comment]
> 
> 
> > I'm accessing my server remotely, and I've installed Organizr's OUI bash script for my ubuntu server which came with nginx.
> 
> I too installed nginx with Organizr script. Try this.
> 
> ```
> server {
>         listen 80; listen [::]:80;
> 	listen 443 ssl http2; listen [::]:443 ssl http2;
>     
> 	include /etc/nginx/config/others/ssl.conf;
> 
> 	server_name speedtest.example.com;
> 	
> 	root /var/www/speedtest-tracker/public;
> 	index index.html index.htm index.php;
> 
> 
> 	location / {
> 		try_files $uri $uri/ /index.php?$args;
> 	location ~ \.php$ {
>        		fastcgi_pass unix:/run/php/php7.4-fpm.sock;
>        	        include snippets/fastcgi-php.conf;
>        	        fastcgi_param SCRIPT_FILENAME $request_filename;
>        	        include fastcgi_params;
>         	}
> 	}
> }
> ```

Wow, this actually worked!
As a subdomain it worked, whereas I tried it as subfolder/app it doesn't. Very weird!

Thanks for the config block @darkknight6722 Appreciate your input.

@henrywhitaker3 the only thing I've tried to narrow down as to why it wasn't working was that I "think" its because the index file. It may be because it was grabbing the wrong one (i.e. trying to use main domain/server block index as opposed to speedtest app)
I had a lot of `Local undefined` errors inside the console as I tried the subfolder rp block.

Nevertheless, it works now!

PS: How did you add org's auth to it?

**Comment by henrywhitaker3** [comment]
Glad it's working for you. Need to update the docs at some point.

For org Auth, you will need to include an Auth location block and do an Auth request to it in the speedtest location block

**Comment by A-Alhashem** [comment]
Thank you!
One last thing before we close this off, is there a way to change the cronjob from 1hr tests to every 3hour?

**Comment by henrywhitaker3** [comment]
Go to the web UI, scroll down to settings and update the schedule input field to `* */3 * * *`and that should do it

**Comment by A-Alhashem** [comment]
> 
> 
> Go to the web UI, scroll down to settings and update the schedule input field to `* */3 * * *` and that should do it

That's exactly what I did, but turns out I have to add a digit to the minute something like `1 * /3 * * *`

cuz it was going bananas doing speedtests every 1minute unless I specify the minute :p

Thanks again!
