### ISSUE TITLE
[BUG] Scheduled tests stoped after 2 days

### ISSUE THREAD

**Issue by 3clypse** [henrywhitaker3/Speedtest-Tracker#387]
**Describe the bug**
After 2 days, the speedtest tracker stop making scheduled or ad-hoc tests.
Is easily visible, because the statistics and table of previous tests are old.

**Docker log**
```
{"type":"log","timestamp":"2020-11-19T00:25:07Z","message":"Error: [11] Cannot read from socket: Resource temporarily unavailable","level":"error"}
No MaxMind license key found; exiting. Please enter your license key into /etc/conf.d/libmaxminddb
run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Context**
 - OS: Unraid + Dockerized
 - Speedtest-Tracker Version: [latest from Docker Hub](https://hub.docker.com/layers/henrywhitaker3/speedtest-tracker/latest/images/sha256-4ef4d448640300c2be01167879814713fb109d5638646df3b5d465bc062377b0?context=explore)

**Additional context**
Rebooting, the problem is solved.

**Comment by henrywhitaker3** [comment]
Looks like that first line of the logs you posted is showing some sort of networking issue. I'm not able to reproduce this, but it may have something to do with your setup?

**Comment by billouetaudrey** [comment]
Hi, same issue here, need to restart the container :'(
