### ISSUE TITLE
Change port of webserver on manual install (non docker)

### ISSUE THREAD

**Issue by josharmour** [henrywhitaker3/Speedtest-Tracker#393]
I'd prefer to not run this with docker so I am attempting to run this on a media server that has other apps running on port 80.

I do have a reverse proxy - nginx.  I could create a location block for it but need to start the service on a different port.

**Comment by henrywhitaker3** [comment]
Well for a manual install, it doesn't really have a default port. The port is decided by nginx, in the docker container, it just listens at port 80 by default

**Comment by josharmour** [comment]
I already had nginx installed prior to following the manual install instructions.  So I need to point nginx at the document root for the web files?

**Comment by henrywhitaker3** [comment]
Sorry, completely missed this. Yeah, so the bit that exposes a port is nginx, not this app
