### ISSUE TITLE
Healthchecks.io doesn't receive notification for scheduled tests

### ISSUE THREAD

**Issue by gbh420** [henrywhitaker3/Speedtest-Tracker#399]
Hi folks. Have started using the docker for this recently on a pi4 so I can check what my vpn on the pi is running at. Firstly, loving the app in general :)

My issue is when testing the notifications after inserting the UUID they are received by healthchecks.io.  It is also fine running a manual speedtest via the gui we I know the notifications generally do work.  When scheduled tests complete I get no notifications though.

I'm on a pi4 so was originally using this version - https://hub.docker.com/r/seltun/speedtest-tracker-armhf   
Then when noticing this I used the script to build my own armhf version using - https://gist.github.com/henrywhitaker3/c6663036a0ae4355843c34cb84859d97

I checked all the logs and didnt see anything in there relating to any failures/errors or anything healthchecks.io related at all   at the times it happened but can provide if needed

edit: I just checked with the logs all tailed and nothing of note happens apart from speedtest/queue.log updating with processing and processed messages in speedtest/queue.log.  The php/error.log has nothing in it for when the tests are completed.

**Comment by henrywhitaker3** [comment]
Oh wow, didn't even know there was an image on docker hub for arm.

Yeah I've been seeing this myself as well. Haven't had much time to work on this recently, but hopefully will have some free time this weekend to have a look at it

**Comment by gbh420** [comment]
Cool. Thanks buddy.

**Comment by henrywhitaker3** [comment]
Pretty sure that PR will fix this

**Comment by gbh420** [comment]
Yeah that looks to be working now on dev Henry. 

On a side note, the automated arm build is also fine.

**Comment by henrywhitaker3** [comment]
Cool, will close for now then.
