### ISSUE TITLE
[BUG] One server giving bad results

### ISSUE THREAD

**Issue by Guillaume-iov42** [henrywhitaker3/Speedtest-Tracker#418]
One server always gives me bad results (about 1/10th of my actual bandwidth) - it's always the same server and it happens quite a lot (maybe once every 5-10 tests, screenshot included). This server is http://lg.lon-c.fdcservers.net:8080 for me (I'm based in London, UK).
Is there a way to somehow exclude it? I don't want to give a whitelist of actual servers, would be nice to have a blacklist of servers to avoid.

![download](https://user-images.githubusercontent.com/45173071/102327538-c85e0980-3f7d-11eb-9a2c-2629d5d96297.png)

**Comment by henrywhitaker3** [comment]
This is a limitation of the Ookla cli. There's only a way to run tests against a specific server, not specify servers to not use. 

Closest you will get is to make a list of servers that you would like to use and add them all to the whitelist

**Comment by Guillaume-iov42** [comment]
Thank you for the answer - great app by the way!
