### ISSUE TITLE
Error when executing a speed test[BUG]

### ISSUE THREAD

**Issue by bjmcintosh** [henrywhitaker3/Speedtest-Tracker#419]
I am using the latest prebuilt docker on an Unraid server. This error seems to have started when I upgraded to the latest docker from the Unraid repository.

The following error appears in the console for the docker:

/config/www/app/Bin/speedtest: Missing argument for option: -s

No speed tests are completed.

Here is the startup log from the docker console:

------------------------------------
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 911
User gid: 911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing...
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-speedtest: executing...
Copying latest site files to config
Database file exists
Env file exists
Running database migrations
Nothing to migrate.
App key exists
JWT secret exists
Slack webhook set, updating db

Not enough arguments (missing: "webhook").

Telegram chat id and bot token unset
Base path is unset
AUTH variable not set. Disabling authentication
Disabling authentication
Clearing old jobs from queue
[cont-init.d] 50-speedtest: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
/config/www/app/Bin/speedtest: Missing argument for option: -s
/config/www/app/Bin/speedtest: Missing argument for option: -s
------------------------------------

**Comment by henrywhitaker3** [comment]
In your settings, is the server field definitely empty? Not just a space or something?

**Comment by bjmcintosh** [comment]
I was going to mention to you on git that the system works great, unless I put something into the server field. I was going to ask you what format the servers in the server field need to be?

 

I had a single server in this format in the field: clgqaspd01.srvr.bell.ca:8080

 

Brian

 

-- 

Brian McIntosh
Columbia Valley Maker Space Communications Guy
info@cvmakerspace.ca <mailto:info@cvmakerspace.ca> 
250 270 0689

**Comment by sean-marks** [comment]
This same issue triggered when I was searching for "LuaJIT version" which I saw appear in my error log, I believe the container is functioning as expected but wasn't sure if this error was a true bug or known issue?

nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)

**Comment by 7opf** [comment]
> In your settings, is the server field definitely empty? Not just a space or something?

I have the same issue with current latest docker image.

My server setting:
```
speedtest01.flashcable.ch:8080,speedtest.solnet.ch:8080
```

**Comment by felho001** [comment]
I don't know why not fix this? nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)

And I today restart wifi router and after speedtest websuite relode only white page, I need stop and start speedtest contanier.

**Comment by lepis0** [comment]
I have the same problem with specific servers.
Everything works if that field is empty but if there is some server address or server id, then it gives error.

Error is:
`/config/www/app/Bin/speedtest: Missing argument for option: -s`

-s option gives next help text:
`-s, --server-id=#                 Specify a server from the server list using its id`


So I think there is some bug in speedtest command with specific server list.

**Comment by lepis0** [comment]
> OS: unraid
> Version: Docker henrywhitaker3/speedtest-tracker:latest
> 
> I have the same problem with specific servers.
> Everything works if that field is empty but if there is some server address or server id, then it gives error.
> 
> Error is:
> `/config/www/app/Bin/speedtest: Missing argument for option: -s`
> 
> -s option gives next help text:
> `-s, --server-id=# Specify a server from the server list using its id`
> 
> So I think there is some bug in speedtest command with specific server list.

I tested with dev docker but the same error appears there.

**Comment by bjmcintosh** [comment]
OK - I feel really stupid. I have been trying to enter a full web site name in the server field of the General Settings section. I should have been putting in the SERVER ID. Leave the field blank, run a few tests and go back and look at the details of the tests (click on arrow on the right and view more info on any test. You will see the server and the Server ID at the top. If you want to select one server to test against, enter the same server ID in the server field 0 a 4 or 5 digit number.

**Comment by lepis0** [comment]
Damn, I tried with server name and server host. Now I tested with ID and it is working.

**Comment by miladahadiani** [comment]
Hi, I have another question...Can I use that for the internal network, I mean having this app just for using my inside network speed between my local servers?
