### ISSUE TITLE
[BUG] Synology Docker-compose: nginx alert

### ISSUE THREAD

**Issue by felho001** [henrywhitaker3/Speedtest-Tracker#430]
**Describe the bug**

**To Reproduce**

nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html) | stdout
-- | --

[error.log](https://github.com/henrywhitaker3/Speedtest-Tracker/files/5744290/error.log)
[access.log](https://github.com/henrywhitaker3/Speedtest-Tracker/files/5744292/access.log)

**Expected behavior**

**Screenshots**

**Context**
 - OS: [e.g Docker, Ubuntu, etc.] Synology docker-compose DSM 6.2.3-25426 Update 3
 - Speedtest-Tracker Version: 1.10.0

**Additional context**

**Comment by henrywhitaker3** [comment]
This all comes from a different base image which I don't make. Out of scope of this project

**Comment by felho001** [comment]
this is interesting because i made it based on the description and it has this compose description in it.

**Comment by felho001** [comment]
> This all comes from a different base image which I don't make. Out of scope of this project

I don't understand why you're writing this? When the docker-compose file under the code was installed. Who did this then?

<img width="1440" alt="Képernyőfotó 2021-01-06 - 14 38 41" src="https://user-images.githubusercontent.com/45117257/103774464-e7a40000-502c-11eb-9a07-3356febf086b.png">

**Comment by henrywhitaker3** [comment]
Look at the dockerfile (the FROM line)

**Comment by felho001** [comment]
> Look at the dockerfile (the FROM line)

where? and this? usaly only white page?
<img width="1440" alt="Képernyőfotó 2021-01-06 - 14 25 01" src="https://user-images.githubusercontent.com/45117257/103774920-9cd6b800-502d-11eb-9cf9-ef4d3b99c2b3.png">

**Comment by felho001** [comment]
it was installed on me. I did everything as described
![Képernyőfotó 2021-01-06 - 14 53 10](https://user-images.githubusercontent.com/45117257/103776176-5da96680-502f-11eb-8a50-41ba994f144d.png)

**Comment by henrywhitaker3** [comment]
Yeah like I've already said, the openresty thing isn't a problem. Ignore it. For the blank page, what's in the logs, what's in the browser console. What have you tried to figure it out?

**Comment by felho001** [comment]
which logs should i check? browser reload, cache event, another browser. neither solves the problem. I use safari, I test chrome and firefox. just shutdown and then restart container.

**Comment by felho001** [comment]
And one more think this: something went wrong running your speedtest. It is a new one 5-8 times a dal bit I dont know why. any idie? 
<img width="1412" alt="Képernyőfotó 2021-01-06 - 20 48 51" src="https://user-images.githubusercontent.com/45117257/103813681-c9f08e00-5060-11eb-8bd2-d74baea9d97d.png">

**Comment by felho001** [comment]
[error.log](https://github.com/henrywhitaker3/Speedtest-Tracker/files/5777899/error.log)

**Comment by felho001** [comment]
why are there so many errors in the test? if i measure a pc speed it is 937Mbs download and the same amount up as well. there are plenty of erroneous measurement results
<img width="1440" alt="Képernyőfotó 2021-01-08 - 20 20 23" src="https://user-images.githubusercontent.com/45117257/104055592-52049e00-51ef-11eb-8d69-8e353048b921.png">

**Comment by felho001** [comment]
hm? 

[2021-01-08 22:11:32.676] [error] Configuration - Couldn't resolve host name (HostNotFoundException)
stdout
21:11:32
[2021-01-08 22:11:32.677] [error] Configuration - Cannot retrieve configuration document (0)
stdout
21:11:32
[2021-01-08 22:11:32.677] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
stdout
21:11:32
[2021-01-08 22:11:32.677] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
stdout
21:11:32
{"type":"log","timestamp":"2021-01-08T21:11:32Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}

**Comment by felho001** [comment]
Hi do you know why the stop auto refresh and if I refresh webpage look oly white siet.
<img width="1440" alt="Képernyőfotó 2021-01-19 - 19 56 07" src="https://user-images.githubusercontent.com/45117257/105080230-cf9e9880-5a90-11eb-9fdb-544e72fdcc33.png">
<img width="1440" alt="Képernyőfotó 2021-01-19 - 19 55 56" src="https://user-images.githubusercontent.com/45117257/105080234-d200f280-5a90-11eb-8645-cbcf134b2f9b.png">
