### ISSUE TITLE
[Feature Request] GeoIP docs

### ISSUE THREAD

**Issue by 7opf** [henrywhitaker3/Speedtest-Tracker#434]
Might be good to add some instructions on getting the geo ip database, currently the only indication is from the log output:

```
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb
```

e.g.:

1. [Create a Mastermind account](https://www.maxmind.com/en/geolite2/signup) to download GeoLite2 database
2. Either download the database and copy `GeoLite2-City.mmdb` to `conf/geoip2db` manually through their download page or write a script.

To script the process, you will need to 
1. [Generate a new license key](https://www.maxmind.com/en/accounts/470036/license-key) 
2. Write a script similar to the one below to download and extract the archive. The extracted directory will contain a file called `GeoLite2-City.mmdb` which should be copied to `conf/geoip2db`:
```
wget -qO- "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${GEOIP_LICENSE_KEY}&suffix=tar.gz" | tar -xvz -C ./
```

**Comment by Serneum** [comment]
Just a heads-up, that link to generate a new key appears to be tied to your account in particular. That being said, I used your little snippet and wrote a small script to run daily. Much appreciated.

```
#!/bin/bash
source .geoip.env

label=$(date +%Y%m%d)
extract_base=/tmp
origin=$extract_base/GeoLite2-City_$label
destination=/data/config/speedtest/geoip2db
name=GeoLite2-City.mmdb

curl -m 10 --retry 5 https://hc-ping.com/$HEALTHCHECK_ID/start

wget -qO- "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=${GEOIP_LICENSE_KEY}&suffix=tar.gz" | tar -xvz -C $extract_base

mv $origin/$name $destination
rm -rf $origin
chown speedtest:media $destination/$name
chmod 664 $destination/$name

curl -m 10 --retry 5 https://hc-ping.com/$HEALTHCHECK_ID/$?
```

Maybe someone else will find it useful

**Comment by henrywhitaker3** [comment]
Yeah I don't do anything with geoip in this project. The base image is from linuxserver which has geoip support built in. You can leave it running without it and it will work fine.
