### ISSUE TITLE
[BUG] Healthchecks.io only works with manually triggered tests

### ISSUE THREAD

**Issue by Serneum** [henrywhitaker3/Speedtest-Tracker#440]
**Describe the bug**
The Healthchecks.io start/success/fail only works when manually clicking Test Again or via the test buttons in the settings. Any automatically triggered test does not call out to Healthchecks.io, so it thinks the Check is down

**To Reproduce**
1. Set up Healthchecks.io
2. Use the test buttons to verify connection to Healthchecks.io
3. Wait for a scheduled run of Speedtest
4. Go to Healthchecks.io and verify that the start/success were not sent, Healthchecks.io thinks the check is down

**Expected behavior**
Queries to Healthchecks.io should work on all speedtests, not just those that were manually triggered

**Screenshots**
![image](https://user-images.githubusercontent.com/1091716/103421336-d27d2c00-4b69-11eb-989c-54e86756b5a6.png)
![image](https://user-images.githubusercontent.com/1091716/103421322-c85b2d80-4b69-11eb-9aee-5d0dcad7d365.png)

**Context**
 - OS: Docker
 - Speedtest-Tracker Version: `latest` from the Docker image

**Comment by AleksCee** [comment]
Same here: only by manual test was healthchecks.io updated.

**Comment by henrywhitaker3** [comment]
This is fixed in the `dev` image, so use that for now
