### ISSUE TITLE
[BUG] Wrong Telegram Notification for threshold percentage exceed

### ISSUE THREAD

**Issue by maik005** [henrywhitaker3/Speedtest-Tracker#441]
Speedtest Tracker Version: 1.10.0

When the ping (maybe also download and upload) threshold is below the threshold alert percentage the text I get on Telegram says:
"For the latest speedtest, the ping value exceeded the absolute threshold"

better would be something like?
"For the latest speedtest, the ping value exceeded the average threshold"

**Comment by felho001** [comment]
How can set telegram notification? I make a personal bot and new chat copy all ID but telegram not work only just slack, but i preferd telegram.

**Comment by maik005** [comment]
you need to configure the Bot-token and Telegram Chat-ID in the notification settings.
You get the Bot-Token from BotFather

**Comment by felho001** [comment]
> you need to configure the Bot-token and Telegram Chat-ID in the notification settings.
> You get the Bot-Token from BotFather

yes but not work. I make botfathertoken and copy bot ID and make one chat copy chat ID but not work

**Comment by maik005** [comment]
it worked fine for me. Which App version of the Speedtest do you have?
Mine is 1.10.0

**Comment by felho001** [comment]
> it worked fine for me. Which App version of the Speedtest do you have?
> 
> Mine is 1.10.0

Same me. 1.10.0

**Comment by aztazt** [comment]
Impossible to make it work either.
I'm indeed in possession of the Bot token, and the Chat ID, but nothing happens when I click on Test notification.

**Comment by felho001** [comment]
> Impossible to make it work either.
> I'm indeed in possession of the Bot token, and the Chat ID, but nothing happens when I click on Test notification.

chat id is 13 caracters number somtimes need before number 100 and - like this -100123456789 here you check correct id: 
https://sean-bradley.medium.com/get-telegram-chat-id-80b575520659

**Comment by aztazt** [comment]
Thank you so much @felho001 !
I had to add a minus sign in front of my chat ID ! Problem solved.
