### ISSUE TITLE
[BUG] Crontab scheduling problems

### ISSUE THREAD

**Issue by corasaniti** [henrywhitaker3/Speedtest-Tracker#451]
I am trying to schedule speedtests at minute 15 every 2 hours at EVEN HOURS If I enter the following schedule
15 * / 2 * * *
the scheduling starts at minute 15 every 2 hours at ODD hours (11.15, 13.15, etc). 

I also set the locale correctly in the docker run command but it didn't work
-e TZ = Europe / Rome 

Thanks

**Comment by henrywhitaker3** [comment]
Might be the spaces in the Cron expression: `15 * / 2 * * *` -> `15 */2 * * *`

**Comment by corasaniti** [comment]
@henrywhitaker3 
Do you think this expression could work?
15 0,2,4,6,8,10,12,14,16,18,20,22 * * *

**Comment by henrywhitaker3** [comment]
Does */2 with no spaces not work? That's how I have mine and runs every 2 hours

**Comment by corasaniti** [comment]
No doesnt works. But this cron expressione would be correct
15 0,2,4,6,8,10,12,14,16,18,20,22 * * *
Right?

**Comment by henrywhitaker3** [comment]
Sorry, didn't see this reply. Yeah that should work, but it just looks like a timezone issue to me. Don't think there should be spaces in `Europe / Rome`, should be `Europe/Rome`
