### ISSUE TITLE
Newbie - sorry - how do I run it

### ISSUE THREAD

**Issue by oserani** [henrywhitaker3/Speedtest-Tracker#452]
Accepted the ookla/GDPR requirements, etc.  Everything seems fine but how do I actually get to the Web UI for this?  My unraid server is on 192.168.4.65.  What do I need to do to have a web page like the demo?  Thanks!

**Comment by henrywhitaker3** [comment]
Pretty sure unraid uses the standard port. So you'd go to <IP>:8765 in the browser

**Comment by oserani** [comment]
Thanks.   Just tried that. I am assuming that I also have to change the port in the docker configuration to 8765?  After I did that, and the docker reloads successfully, pointing the browser to xxx:8765 gives me connection refused on the browser.


Thanks again!

**Comment by henrywhitaker3** [comment]
Nope, I think unraid has that as default if you added it through the unraid app store thing. It just opens port 8765 on the unraid hosts and maps it to port 80 in the container

**Comment by oserani** [comment]
I must be missing something - like maybe do I need to build a website to look a the data?  Below is what I see on the docker screen on unraid.  The port is not mapped on the unraid side, so when I click on the Web GUI option on the speed-tracker icon, it just opens another window with the main unraid screen and the configuration screen for the docker.  Thanks again for your patience.

<img width="2490" alt="Screen Shot 2021-01-13 at 4 36 23 " src="https://user-images.githubusercontent.com/76915507/104513401-9613ec00-55bd-11eb-8659-3817a728e897.png">

<img width="2323" alt="Screen Shot 2021-01-13 at 4 33 08 " src="https://user-images.githubusercontent.com/76915507/104513219-4a614280-55bd-11eb-9095-70b6bb5f9a5c.png">

**Comment by henrywhitaker3** [comment]
Ah okay, on the config page (first screenshot) put a port number there, like 8765, save and wait for the container to start. Then you should be good

**Comment by oserani** [comment]
Looks like I got it this time - no idea what it’s different but seems to be working… container mapped to 8765 and now the WebUI points to something… thanks again for all your help!

**Comment by oserani** [comment]
Hi Henry - this stopped working for some reason - I see (what I think is a new message) on the log something about having to manually download GeoIP2, but when I go to that site, I am utterly confused on what I need.  Can you shed some light?  Thanks!

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 911
User gid: 911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing...
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-speedtest: executing...
Copying latest site files to config
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 911
User gid: 911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing...
Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-speedtest: executing...
Copying latest site files to config
Database file exists
Env file exists
Running database migrations
Nothing to migrate.
App key exists
JWT secret exists
Slack webhook set, updating db


Not enough arguments (missing: "webhook").


Telegram chat id and bot token unset
Base path is unset
AUTH variable not set. Disabling authentication
Disabling authentication
Clearing old jobs from queue
[cont-init.d] 50-speedtest: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
