### ISSUE TITLE
[BUG] every "Show results for the last days" change add every time a new Interval-Event

### ISSUE THREAD

**Issue by AleksCee** [henrywhitaker3/Speedtest-Tracker#453]
**Describe the bug**
By changing the "Show results for the last days" value - I wondering about more and more request on the api/speedtest.
After some debugging, I think that the setInterval function in the Components seams to add every Time. So if you change the value of days 3 Times you have 4 intervals for the same refresh api-Request.

**To Reproduce**
Load the page, open dev-webConsole and wait. The requests /api/speedtest/last,config and 7 will display every 10 seconds.
Now change the "show last days" value 3 times and watch the occurs of the api-calls.

**Expected behavior**
Not so many request after change the "Show days" value. Only a reload every 10 seconds like the default interval in the components is set.

**Context**
 - OS: Docker, Firefox (84.0.2) on macOS, 
 - Speedtest-Tracker Version: 1.10.3

**Comment by AleksCee** [comment]
I think I have found it. After wrapping the clearInterval function with consol.log-output I see every time on change the value an undefined. So taking a deeper look at the Code:
https://github.com/henrywhitaker3/Speedtest-Tracker/blob/0b8c633a754e320d06f52e86dc16c94b8480a284/resources/js/components/Graphics/HistoryGraph.js#L245
```
if(days) {
            this.getData(days);
            clearInterval(this.state.int);
            var int = setInterval(this.getData, 10000);
            toast.info('Showing results for the last ' + days + ' days');
            this.setState({
                days: days,
                interval: int
            });
        }	
```

I think the line 245 should be:  clearInterval(this.state.interval); not .int - hope I'm right.

**Comment by henrywhitaker3** [comment]
Just merged this, is in the `dev` docker image
