### ISSUE TITLE
[BUG] Scheduled tests consistently fail after a 2-3 cycles

### ISSUE THREAD

**Issue by dra2885** [henrywhitaker3/Speedtest-Tracker#461]
I've got this setup in a docker container on my NAS. It starts up fine and will run a few tests with no problem (both manual and scheduled).

I'll leave it and come back a day or two later to find that at some point, the scheduled tests failed. A peek at the log reveals this unhelpful entry:

`{"type":"log","timestamp":"2021-01-17T02:12:05Z","message":"Error: [11] Cannot read: Resource temporarily unavailable","level":"error"}`

The only way to get tests running again is to restart the container.

Running docker ce 18.09.8.

Any suggestions on troubleshooting or diagnosis next steps?

**Comment by dra2885** [comment]
For what it's worth, I've gotten a half-step further in diagnosing this. It seems that a job (whether scheduled manually or the scheduleder) will randomly hang. If I go into the container and identify the correct pid, I can kill it and get jobs restarted.

Still no idea what is randomly causing jobs to hang...

**Comment by henrywhitaker3** [comment]
Gonna close this as it's v old (and I was rubbish and didn't get round to looking at it) but did you ever figure it out?
