### ISSUE TITLE
[BUG]Error: something went wrong running your speedtest

### ISSUE THREAD

**Issue by felho001** [henrywhitaker3/Speedtest-Tracker#468]
**Describe the bug**
no speedtest Mányoki times wrong. I need stop and restart container.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context**
 - OS: [e.g Docker, Ubuntu, etc.] docker compose synology
 - Speedtest-Tracker Version: 1.10.0
<img width="1440" alt="Képernyőfotó 2021-01-20 - 18 38 43" src="https://user-images.githubusercontent.com/45117257/105213712-53b75580-5b4f-11eb-9b7b-c4c11d09bd09.png">

**Additional context**

**Comment by felho001** [comment]
<img width="1440" alt="Képernyőfotó 2021-01-21 - 12 13 34" src="https://user-images.githubusercontent.com/45117257/105343586-1cde4f80-5be2-11eb-87de-25eff9b1e4dc.png">
Why to many wrong test i try now dev version but same wrong latest.......

**Comment by henrywhitaker3** [comment]
What's in the logs?

**Comment by felho001** [comment]
I ask you before which logs and where can I find. If you sad I download and rend you.

**Comment by henrywhitaker3** [comment]
Docker logs

**Comment by felho001** [comment]
docker no error log
<img width="1440" alt="Képernyőfotó 2021-01-21 - 12 34 07" src="https://user-images.githubusercontent.com/45117257/105345804-ff5eb500-5be4-11eb-9e55-a1322763d904.png">
<img width="1440" alt="Képernyőfotó 2021-01-21 - 12 33 32" src="https://user-images.githubusercontent.com/45117257/105345814-02f23c00-5be5-11eb-9bf3-7e59a48ea11e.png">

in speedtest container : it is not necessary to look for the error logs inside the container?

**Comment by henrywhitaker3** [comment]
`docker logs <container-name>`

**Comment by felho001** [comment]
i only see what i attached in the previous post. I dont now how can find this docker logs speedtest in synology

**Comment by felho001** [comment]
<img width="1440" alt="Képernyőfotó 2021-01-21 - 12 44 53" src="https://user-images.githubusercontent.com/45117257/105346927-7c3e5e80-5be6-11eb-94a4-b6f8d919bd1e.png">

**Comment by felho001** [comment]
really no one can not help anyone else who uses synologyn no problem? And ágain white page

**Comment by felho001** [comment]
docker logs speedtest 
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1024
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing... 
GeoIP2 database found
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-speedtest: executing... 
Copying latest site files to config
Database file exists
Env file exists
Running database migrations
Nothing to migrate.
App key exists
JWT secret exists
Slack webhook is unset
Telegram chat id and bot token set, updating .env
Telegram options updated
Base path is unset
AUTH variable not set. Disabling authentication
Disabling authentication
Clearing old jobs from queue
[cont-init.d] 50-speedtest: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1024
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing... 
GeoIP2 database found
[cont-init.d] 40-config: exited 0.
[cont-init.d] 50-speedtest: executing... 
Copying latest site files to config
Database file exists
Env file exists
Running database migrations
Nothing to migrate.
App key exists
JWT secret exists
Slack webhook is unset
Telegram chat id and bot token set, updating .env
Telegram options updated
Base path is unset
AUTH variable not set. Disabling authentication
Disabling authentication
Clearing old jobs from queue
[cont-init.d] 50-speedtest: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)

**Comment by felho001** [comment]
[2021-01-28 04:15:09] local.ERROR: Undefined index: ping  
[2021-01-28 04:45:09] local.ERROR: Undefined index: ping  
[2021-01-28 17:00:17] local.ERROR: Undefined index: ping  
[2021-01-28 19:45:17] local.ERROR: Undefined index: ping

**Comment by felho001** [comment]
[2021-01-29 00:03:35] local.ERROR: file_put_contents(/config/www/storage/framework/cache/data/37/24/37246234cdba9eafcda0eb4e6953564f4b57fcdf): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_put_contents(/config/www/storage/framework/cache/data/37/24/37246234cdba9eafcda0eb4e6953564f4b57fcdf): failed to open stream: No such file or directory at /config/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:135)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten...', '/config/www/ven...', 135, Array)
#1 /config/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(135): file_put_contents('/config/www/sto...', '1611878675i:161...', 2)
#2 /config/www/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put('/config/www/sto...', '1611878675i:161...', true)
#3 /config/www/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(211): Illuminate\\Cache\\FileStore->put('52f22fbd6e8eddb...', 1611878675, 60)
#4 /config/www/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(316): Illuminate\\Cache\\Repository->put('52f22fbd6e8eddb...', 1611878675, 60)
#5 /config/www/vendor/laravel/framework/src/Illuminate/Cache/RateLimiter.php(60): Illuminate\\Cache\\Repository->add('52f22fbd6e8eddb...', 1611878675, 60)
#6 /config/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(57): Illuminate\\Cache\\RateLimiter->hit('52f22fbd6e8eddb...', 60)
#7 /config/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 200, '1')
#8 /config/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 /config/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#10 /config/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#11 /config/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#12 /config/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#13 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#14 /config/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#15 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /config/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /config/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /config/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /config/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /config/www/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /config/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /config/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /config/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /config/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 /config/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#30 /config/www/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#31 {main}
"} 
[2021-01-29 00:45:10] local.ERROR: Undefined index: ping  
[2021-01-29 05:45:14] local.ERROR: Undefined index: ping

**Comment by felho001** [comment]
here the long when speedtest wrong  but I dont know why. And the page reload many times white page. I use one other coantiner name is bazarr look like this when I relod page always white page load, and i  change 127.0.0.1 config ip and rewrite this 0.0.0.0  now it work. Is it not work speedtest same? If yes where find the config file where i neked change ip.
[laravel-2021-01-29.log](https://github.com/henrywhitaker3/Speedtest-Tracker/files/5896348/laravel-2021-01-29.log)
<img width="1042" alt="Képernyőfotó 2021-01-29 - 22 14 36" src="https://user-images.githubusercontent.com/45117257/106328038-6a605980-627f-11eb-9a2a-573cb0457260.png">

**Comment by albertxiao** [comment]
got same issue, here's the docker logs:

`Slack webhook updated
Telegram chat id and bot token unset
Base path is unset
AUTH variable set. Enabling authentication
Enabling authentication
Clearing old jobs from queue
[cont-init.d] 50-speedtest: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
{"type":"log","timestamp":"2021-04-03T07:00:05Z","message":"Failed to resolve host name. Cancelling test suite.","level":"error"}
{"type":"log","timestamp":"2021-04-03T07:01:29Z","message":"Failed to resolve host name. Cancelling test suite.","level":"error"}
{"type":"log","timestamp":"2021-04-03T07:02:10Z","message":"Failed to resolve host name. Cancelling test suite.","level":"error"}
{"type":"log","timestamp":"2021-04-03T07:04:48Z","message":"Failed to resolve host name. Cancelling test suite.","level":"error"}`
