### ISSUE TITLE
log ist spammed with error[BUG]

### ISSUE THREAD

**Issue by Serph91P** [henrywhitaker3/Speedtest-Tracker#492]
**Describe the bug**
This appeared out of nowehre. First it worked fine now the tests dont work and the log is spammed with an error message.

**To Reproduce**
Run a speedtest?

**Expected behavior**
That a speedtest is run with no error and the numbers are outputted and not 0

**Screenshots**
![image](https://user-images.githubusercontent.com/8904984/106868498-216d3280-66cf-11eb-9653-8c97173f25fb.png)

![image](https://user-images.githubusercontent.com/8904984/106868435-0f8b8f80-66cf-11eb-9a74-e7eba1f86051.png)

**Context**
 - OS: Unraid Docker
 - Speedtest-Tracker Version:  1.10

**Additional context**
Would be great if I knew how to fix this tried restarting ect. nothing realy helps. The test just suddenly stopped working.

**Comment by Serph91P** [comment]
Seems it was my pihole suddenly blockin it?

**Comment by henrywhitaker3** [comment]
Yeah that looks like errors coming from the ookla cli. Maybe one of the blacklists you have in pihole has started blocking a domain it uses to get a server list?
