### ISSUE TITLE
[Support] Add speedtest-server for high bandwith connections

### ISSUE THREAD

**Issue by JAKAMI99** [henrywhitaker3/Speedtest-Tracker#494]
**How do I add servers?**
As mentioned in #71 there are some folks that havev issues with faster connections and the random server selection.
I tried figuring out how you could add only fast servers which provide >1 Gbit/s bandwith per user.
The only thing I found when searching for speedtest server was: https://gist.github.com/gxgani/11401911
Now i wonder what do I add?
Do i had the URL including the "upload.php"?
I searched for documentations, maybe im blind but found nothing.

**Asked Informations**
Where do I get currently active speedtest.net-server?
How do I got the information needed to add them
In which format do I add them?

Btw, thanks for the awesome project, runs smooth on my Unraid-Server.

**Comment by philippjess** [comment]
Set the Server ID in general settings.

**Comment by henrywhitaker3** [comment]
Yeah the actual running the speedtest bit is not my code, but Ookla/speedtest.net's own binary, which picks a server (I'm assuming) the same way the website does.

**Comment by JAKAMI99** [comment]
Thanks, I didnt knew that. :) Thanks for the answer
