### ISSUE TITLE
[Feature Request] Ability to set MaxMind license key as environment variable

### ISSUE THREAD

**Issue by JesseyWhite** [henrywhitaker3/Speedtest-Tracker#504]
While looking at the logs, I noticed that it searches for a license key on a weekly basis for MaxMind. It would be most helpful to be able to set this key as an environment variable than as a volume mount.

**Additional context**
![image](https://user-images.githubusercontent.com/49629699/108558248-4365d800-72bf-11eb-8032-62371de1a72b.png)

**Comment by henrywhitaker3** [comment]
Comes from the base image, have just looked at their docs and it can be set with `MAXMIND_LICENSE_KEY` env var. Although nothing in this project is using it, so it doesn't need setting
