### ISSUE TITLE
[BUG] Server selection

### ISSUE THREAD

**Issue by Wajasful** [henrywhitaker3/Speedtest-Tracker#509]
I want to select just one server instead of random server but is not working.
Is there a special thing to make this feature working ? Thanks

![image](https://user-images.githubusercontent.com/70446704/109320789-b5569800-7850-11eb-8340-57302fef4c23.png)

**Comment by SuperstalkerX** [comment]
Could you be more descriptive on how it is not working?

**Comment by darthspartan** [comment]
It uses the server ID number not the URL or Server IP. It was messing me up too. The only bug here is not directly stating that in the UI. Should definitely say “Uses Server ID” somewhere.

**Comment by Wajasful** [comment]
Okay, it's maybe the problem. I was typing the URL of the server.
Where can we found the server's ID ?

Thanks


Jules RAMBAULT
+33626685214

Le sam. 27 févr. 2021 à 5:00 PM, darthspartan <notifications@github.com> a
écrit :

**Comment by Wajasful** [comment]
> It uses the server ID number not the URL or Server IP. It was messing me up too. The only bug here is not directly stating that in the UI. Should definitely say “Uses Server ID” somewhere.

Okay, it's maybe the problem. I was typing the URL of the server.
Where can we found the server's ID ?

**Comment by henrywhitaker3** [comment]
Will add it to the UI when I'm next working on this (been a while, I know). Re getting the server ID, they're all in an XML file on speedtest.net somewhere I can't remember, or you can click the little arrow thing to see more info about a specific speedtest result and the ID will be in the modal that pops up

**Comment by krh1009** [comment]
I found IDs here: https://c.speedtest.net/speedtest-servers-static.php
