### ISSUE TITLE
"Exec format error" when running php artisan speedtest:eula 

### ISSUE THREAD

**Issue by wtrdk** [henrywhitaker3/Speedtest-Tracker#511]
I would love to run this tool on a raspberry pi (with dietpi as OS). When following the manual install instructions, I run into the following error.
```
php artisan speedtest:eula
sh: 1: /home/dietpi/Speedtest-Tracker/app/Bin/speedtest: Exec format error

```
I get the same kind of error when running this:
```
php artisan speedtest:run
Running speedtest, this might take a while...
sh: 1: /home/dietpi/Speedtest-Tracker/app/Bin/speedtest: Exec format error
Something went wrong running the speedtest.
```

Can anyone help me set this up? Thanks!

**Comment by henrywhitaker3** [comment]
You sure you downloaded the arm version of the Ookla binary?

**Comment by wtrdk** [comment]
Thanks, Henry, for your quick response!
I feel so stupid... Changing it to the arm version works like a charm!!

**Comment by henrywhitaker3** [comment]
No worries, glad it working
