### ISSUE TITLE
[Feature Request] Discord notifications

### ISSUE THREAD

**Issue by Berserkir-Wolf** [henrywhitaker3/Speedtest-Tracker#527]
**Describe the feature**
I'd like the ability to use Discord webhook notifications instead of Slack. This will allow for HomeAssistant to see the notification, parse the output, and perform an action if there's an issue (like automatically reboot the router if the download is slower than a given speed).

**Comment by henrywhitaker3** [comment]
Add `/slack` to the end of your discord webhook and it will work

**Comment by Berserkir-Wolf** [comment]
Wow, TIL. That's awesome.
Thanks for that!

**Comment by thiagottss** [comment]
It didn't work for me...
