### ISSUE TITLE
Exclusion of some servers

### ISSUE THREAD

**Issue by corasaniti** [henrywhitaker3/Speedtest-Tracker#533]
There are some servers that have very high ping times and I would like to exclude them.
It would be nice to have the option to exclude servers in the settings.
Thanks

PS:
I still can't start the latest-arm version

```
sudo apt-get install libseccomp2/buster-backports

pi@twisteros:~ $ sudo apt-get install libseccomp2/buster-backports
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Release 'buster-backports' for 'libseccomp2' was not found
```

**Comment by henrywhitaker3** [comment]
Don't have a spare pi atm to try it, but may need to add an apt repo that has the right version of libseccomp2 in there.

The exclusion thing has been raised before, it's only possible to choose a server with the binary the backend uses to run the tests, closest you'll get is adding a bunch of servers you're okay with on the settings page
