### ISSUE TITLE
Doesn't ping healthchecks.io after completion.

### ISSUE THREAD

**Issue by fzlrog** [henrywhitaker3/Speedtest-Tracker#534]
I have my speedtest-tracker exposed to the web via nginx reverse proxy.
It runs every 6 hours like I set it to, but for some reason it doesn't ping healthchecks.io after completion.
I've tried both latest and dev to make sure it wasn't a problem with one of them. Starting to suspect it might be a problem maybe with the nginx reverse proxy?

When using the test buttons it works, so I have the right UUID.

**Context**
 - OS: Manjaro running it via Docker
 - Speedtest-Tracker Version: 1.10.4

**Comment by ionutz89** [comment]
how did you manage to fix this issue? I am getting same problem.

**Comment by fzlrog** [comment]
I didn't, it sort of fixed itself after I just left it running for a couple of tests. 
Darndest thing.
