### ISSUE TITLE
Add Note under Speedtest Server list field to show what the format should be

### ISSUE THREAD

**Issue by CSRAutomator** [henrywhitaker3/Speedtest-Tracker#538]
**Describe the feature**
Should this be the name of the Speedtest.net server in my area? Should it be my city name? Should it be a URL to the server?  Is there some kind of identifier I should be using?  No-one knows and there is no description of what this field requires.

Perhaps add a comment about where to find the identifiers for Speedtest.net Servers in your area as well.
Perhaps add this link....  https://c.speedtest.net/speedtest-servers-static.php

**Additional context**
![image](https://user-images.githubusercontent.com/25186319/112201788-9b556e80-8bde-11eb-9982-9be2a139fda4.png)

Thanks.

**Comment by birryk** [comment]
It's the id close to the end of each line.

**Comment by fritolays** [comment]
Yeah, this would be pretty helpful heh

**Comment by henrywhitaker3** [comment]
Just merged this, is in the `dev` docker image
