### ISSUE TITLE
[Feature Request] Support customizing the server used by speedtest-cli

### ISSUE THREAD

**Issue by craSH** [henrywhitaker3/Speedtest-Tracker#54]
Feature request - support providing a configurable server ID for `speedtest-cli` to use (i.e. `speedtest-cli --server 6057`) - this may yield more consistent results or allow for testing specific paths (such as cross-country, instead of just locally to test your speed to things near by).

I'm using your Docker container - having this configurable via an environment variable wold be excellent (perhaps `SPEEDTEST_SERVER_ID=6057`, and if nothing is provided it can continue to not pass the argument, resulting in automatic server selection.

Alternatively, you could just allow for an environment variable or configuration option to specify the complete `speedtest-cli` command line, allowing for more advanced configuration if desired by the user.

Thanks!

**Comment by henrywhitaker3** [comment]
Like with the other issue you created, it's a good suggestion. I'll implement this when my schedule frees up a bit (in a few weeks)

**Comment by henrywhitaker3** [comment]
Added in v1.4.1

**Comment by craSH** [comment]
Again, awesome to have this added so quickly, thank you! I'll be testing it out over the next few days.
