### ISSUE TITLE
[BUG] Timezone BST not working as expected

### ISSUE THREAD

**Issue by ionutz89** [henrywhitaker3/Speedtest-Tracker#545]
**Describe the bug**
It seems the cronjob does not work properly with the BST timezone. 

**To Reproduce**
Steps to reproduce the behaviour:
I tried to hardcode in docker container timezone and in `php-local.ini`:

```
#cat /config/php/php-local.ini
date.timezone = Europe/London
# date
Mon Mar 29 20:24:36 BST 2021

```

Unless is somewhere else that I need to change, I am not sure what else to troubleshoot.
I am running on a Docker container on Ubuntu 20.04 on RPi 4 using latest version of Speedtest-Tracker 1.10.4

**Comment by ProjectVRD** [comment]
> **Describe the bug**
> It seems the cronjob does not work properly with the BST timezone.

Out of curiosity do all scheduled speedtests fail?

This is the issue I have and I am using the BST timezone. Manual speedtests seem to be fine.

**Comment by henrywhitaker3** [comment]
Will sort out BST for the schedule this weekend. 

This shouldn't affect tests passing/failing, just when they run. There anything in the docker logs?

**Comment by ionutz89** [comment]
> Out of curiosity do all scheduled speedtests fail?

Yes, it is working.

**Comment by ionutz89** [comment]
> Will sort out BST for the schedule this weekend.
> 
> This shouldn't affect tests passing/failing, just when they run. There anything in the docker logs?

From inside docker container on `/config/log/speedtest/cron.log`

```Running scheduled command: '/usr/bin/php7' 'artisan' speedtest:clear-sessions > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7' 'artisan' speedtest:clear-sessions > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7' 'artisan' speedtest:clear-sessions > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7' 'artisan' speedtest:clear-sessions > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7' 'artisan' speedtest:clear-sessions > '/dev/null' 2>&1
```
 Or  from `/config/log/speedtest/queue.log`:
 
 ```
 [2021-03-31 15:15:20][558] Processed:  App\Jobs\SpeedtestJob
[2021-03-31 18:15:01][559] Processing: App\Jobs\SpeedtestJob
[2021-03-31 18:15:18][559] Processed:  App\Jobs\SpeedtestJob
```
 On docker logs container is only from docker startup:
 
 ```Disabling authentication
Clearing old jobs from queue
chown: changing ownership of '/config/php/php-local.ini': Read-only file system
[cont-init.d] 50-speedtest: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by henrywhitaker3** [comment]
Just merged this, try the `dev` docker image. It will need you to add the env var `TZ=Europe/London` to get BST working
