### ISSUE TITLE
[Suggestion] Use JSON output from speedtest-cli for simpler and more reliable parsing

### ISSUE THREAD

**Issue by craSH** [henrywhitaker3/Speedtest-Tracker#55]
Hi, I was just browsing your code and see that you are using the standard ("simple") output mode from `speedtest-cli`, doing regex matching to collect the results.

It may be worth looking into `speedtest-cli`'s JSON output mode, which is intended to be used with programatic interfaces like this. It provides a bit more data which could be handy to include in test logs and expose in the UI, but more importantly it will be a more reliable interface to parse results from, and it is natively machine readable by PHP's `json_decode` (https://www.php.net/manual/en/function.json-decode.php). It's more reliable due to the fact that the friendly/simple output from `speedtest-cli` may change from version to version, but the JSON format is defined and less likely to change over time.

Thanks!

**Comment by henrywhitaker3** [comment]
Hadnt actually looked to see if it had one, but yeah a JSON output mode would be way better. 

Won't be able to implement this change for a few weeks, but is now at the the top of the list

**Comment by craSH** [comment]
Solid work on the quick turn around with this, thanks!
