### ISSUE TITLE
How is the sytanx to add servers in the server field?

### ISSUE THREAD

**Issue by poltrian** [henrywhitaker3/Speedtest-Tracker#550]
i try e.g  http://st.psw.net/speedtest/upload.php or speedtest.uit.one:8080

**Comment by poltrian** [comment]
Found it, ist the Server ID. Perhaps a little note under the field?

**Comment by henrywhitaker3** [comment]
Just merged this, is in the `dev` docker image

**Comment by nickm324** [comment]
Where is this updated information. I cannot find anything anywhere that gives and specifics to how to enter servers and using the IDs like 2014,20176 makes it just fail.

**Comment by 2fst4u** [comment]
> Where is this updated information. I cannot find anything anywhere that gives and specifics to how to enter servers and using the IDs like 2014,20176 makes it just fail.

Same issue here. Adding an ID makes the test fail but removing it allows the test to work again.
