### ISSUE TITLE
Multiarch container

### ISSUE THREAD

**Issue by ElCucoEnPersona** [henrywhitaker3/Speedtest-Tracker#552]
It would be nice to have a multiarch version in docker hub, instead of having to declare arch.

**Comment by peanutbother** [comment]
I already did that in my fork of the alpha branch.
For now my build chain clones this repo and builds it against amd64/arm64/armv7.

see https://github.com/peanutbother/docker-speedtest & https://hub.docker.com/r/bricksoft/speedtest

Maybe @henrywhitaker3 might want to integrate my workflows into this repo?

**Comment by henrywhitaker3** [comment]
Could do tbf,  currently building them in docker hub, but will have a look at your repo when I've got some time 👍

**Comment by henrywhitaker3** [comment]
Nice one @peanutbother - finally got round to doing it
