### ISSUE TITLE
Dev 1.11.1 gets GET api/speedtest/home/7 500 Internal Server Error

### ISSUE THREAD

**Issue by AleksCee** [henrywhitaker3/Speedtest-Tracker#562]
After update the Docker-dev image the following error is occurs:

{
    "message": "Call to undefined function App\\Http\\Controllers\\run()",
    "exception": "Error",
    "file": "/config/www/app/Http/Controllers/HomepageDataController.php",
    "line": 29,
    "trace": [
        {
            "file": "/config/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "__invoke",
            "class": "App\\Http\\Controllers\\HomepageDataController",
            "type": "->"
        },
        {
            "file": "/config/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"

**Comment by henrywhitaker3** [comment]
Yeah noticed that after it merged. Could you try pulling the image again, I pushed a fix which should've sorted it

**Comment by AleksCee** [comment]
Great, thanks - work fine again! Thanks for the quick fix!!!!

**Comment by AleksCee** [comment]
Just for interesting, what is the fix? I can’t see a commit since the issue. But I like to understand what’s happened. 
Thanks, Alex

**Comment by henrywhitaker3** [comment]
Have a look at this commit a3f9593c294593d3efae8549d9ea92fae5bd24e1

**Comment by henrywhitaker3** [comment]
Just managed to break it again, don't pull for half an hour lol

**Comment by AleksCee** [comment]
@henrywhitaker3 have you update some features or bugs or why break it again? Should I update again if it’s work again or is this the same version?

**Comment by henrywhitaker3** [comment]
Pushed a fix like 10 mins ago, should be working fine if you pull again
