### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by nickm324** [henrywhitaker3/Speedtest-Tracker#571]
**Describe the feature**
Add some documentation that gives some level of specifics on what format the the servers info is supposed to be entered in the Server field under settings.

Doesn't make a lot of sense just to say enter a list of speed test servers comma separated.
Where do you get the list of servers, what needs to be entered into the Server field specifically.

**Comment by madtempest** [comment]
This is old, but give it a whirl to get the server IDs - https://github.com/sivel/speedtest-cli

**Comment by KossikCZ** [comment]
This [link](https://williamyaps.github.io/wlmjavascript/servercli.html) is one of the options for sure.
Alternatively, people can download the official cli version of speedtest and run speedtest.exe --servers which lists the closest ones.

**Comment by henrywhitaker3** [comment]
Yeah it's server IDs. The latest `dev` image now has that specified
