### ISSUE TITLE
[BUG] Cant Delete Failed tests

### ISSUE THREAD

**Issue by tris203** [henrywhitaker3/Speedtest-Tracker#582]
**Describe the bug**
If a test has failed and shows a red x, it cant be deleted from the results

**To Reproduce**
1. Have a failed test
2. Visit All Tests page
3. Observe that it cannot be deleted

**Expected behavior**
Option to remove a failed test

**Additional context**
I have a had network issues where i know the test would fail (firewall down for maintence) so I would like to remove the failed test from the logs

**Comment by henrywhitaker3** [comment]
#556
