### ISSUE TITLE
Graph does not change when setting results for the last XX days[BUG]

### ISSUE THREAD

**Issue by clowrym** [henrywhitaker3/Speedtest-Tracker#589]
**Describe the bug**
Changing the amount of days to show results does not change the graphs anymore

**To Reproduce**
1.go to Show results
2. change to more days
3. this pops up
![image](https://user-images.githubusercontent.com/25108950/116448799-bd15c700-a816-11eb-9526-5fdb614ebeda.png)

**Expected behavior**
Graph should change to displayed days, but 7 days remain

**Screenshots**
![image](https://user-images.githubusercontent.com/25108950/116449337-4deca280-a817-11eb-9b48-6d3d7c81f7ba.png)

**Context**
 - OS: Docker (running on unraid Host)
 - Speedtest-Tracker Version: 1.12.0

**Additional context**
approx. 4wks ago speedtest stopped working on the Cron schedule (Set to hourly tests). I had to remove all Docker/program files and start from scratch on April 14th. Hoursly tests have been working fine since, I have not been able to view more then 7 days on the graphs

**Comment by henrywhitaker3** [comment]
There anything in the browser console?

**Comment by clowrym** [comment]
not sure what im looking for there....
![image](https://user-images.githubusercontent.com/25108950/116816894-205a6e80-ab21-11eb-9ae4-d0e24b199ed8.png)

**Comment by clowrym** [comment]
full console output
![image](https://user-images.githubusercontent.com/25108950/116817134-31f04600-ab22-11eb-83ca-ba84d0f39e7e.png)

**Comment by henrywhitaker3** [comment]
Should have been sorted in #680
