### ISSUE TITLE
[BUG] standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by grasuoare** [henrywhitaker3/Speedtest-Tracker#597]
Hi,

Could you help me figure it out why i have the following error in the log file?

standard_init_linux.go:219: exec user process caused: exec format error

I'm using Raspberry Pi 4 and the code created in docker compose is:

  speedtest:
    container_name: speedtest
    hostname: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8765:8765
    restart: always
    volumes:
      - /home/pi/docker/speedtest:/config
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    environment:
      - OOKLA_EULA_GDPR=true

Thanks in advance,

Paul

**Comment by amastelek** [comment]
Looks like there is only a docker for x86 and it needs one for arm.

**Comment by henrywhitaker3** [comment]
Use the tag `latest-arm` or `dev-arm`

**Comment by olvier** [comment]
leads me to:

![image](https://user-images.githubusercontent.com/13106409/131253354-09e2a31e-2c6f-456b-96c2-1801d8a5e66c.png)

Any idea?
