### ISSUE TITLE
PID and GID defaulting to 1000:root

### ISSUE THREAD

**Issue by robflate** [henrywhitaker3/Speedtest-Tracker#61]
I used the following env variables in my docker compose;
```
APPLICATION_UID: 501
APPLICATION_GID: 999
```
If I bind mount a volume, the folder on my local file system is initially owned by `root:root` then this changes to `1000:root` rather than `501:999`. How should I correctly set the UID and GID?

Thanks.

**Comment by henrywhitaker3** [comment]
Doesn't seem like there's an easy way to do that from looking at the docs for the base image I've used. I'll be remaking the docker image using a different base image to support ARM devices as well and will most likely base it on [linuxserver/nginx](https://hub.docker.com/r/linuxserver/nginx) which has support for setting UID and GID. I'll comment on and close this issue when I push out that update.

**Comment by henrywhitaker3** [comment]
Okay, have switched over to a different base image now. Can you try using `henrywhitaker3/speedtest-tracker:dev` where you can set user and group id in env vars using `PUID` and `PGID`
