### ISSUE TITLE
[Feature Request] Authentication option to help minimise the security risk to the network and host device

### ISSUE THREAD

**Issue by ProjectVRD** [henrywhitaker3/Speedtest-Tracker#620]
Addition of an option to allow users to authenticate into the application with a choice of basic authentication (pop-up in browser) and via a Login Form. Username and Password would accept up to 60 alphanumeric characters and special characters.

This would instantly close off a vulnerability where there is no authentication option to access the application and potentially the environment values that it is utilising.

**Comment by henrywhitaker3** [comment]
This is already a thing, did you even read the readme?
