### ISSUE TITLE
[BUG] - Dev Build - Show Results For The Last x Days - Not Working

### ISSUE THREAD

**Issue by Jiriteach** [henrywhitaker3/Speedtest-Tracker#630]
On the build build - if I try filter results to another period of time (1 day as an example), the graphs do not change to reflect this.

This is working on the release build.

**Comment by clowrym** [comment]
Same issue i have... I can't seem to downgrade though, doesnt work after!!

[https://github.com/henrywhitaker3/Speedtest-Tracker/issues/589#issue-870198478](url)

**Comment by henrywhitaker3** [comment]
Should be sorted now @Jiriteach  @clowrym in #680
