### ISSUE TITLE
[Feature Request] Web API to query data

### ISSUE THREAD

**Issue by agneevX** [henrywhitaker3/Speedtest-Tracker#633]
**Describe the feature**

Is there a way I can get data for the last x days or x hours in an API, so that I can integrate this data in apps like Home Assistant? Thanks

**Additional context**
N/A

**Comment by henrywhitaker3** [comment]
Can't remember the exact endpoint, but there is one for last X days. Run `php /config/www/artisan route:list` and it will be one of the routes listed there

**Comment by agneevX** [comment]
Thanks. Can this be documented in the wiki?
