### ISSUE TITLE
Latest version not working, issue with speedtest cli

### ISSUE THREAD

**Issue by jbrizz** [henrywhitaker3/Speedtest-Tracker#644]
Running the latest version and tests won't start. Configured as recommended.

Log is as follows

[2021-06-30 22:00:08.172] [error] Trying to get interface information on non-initialized socket.

[2021-06-30 22:00:13.689] [error] Configuration - Couldn't resolve host name (HostNotFoundException)

[2021-06-30 22:00:13.689] [error] Configuration - Cannot retrieve configuration document (0)

[2021-06-30 22:00:13.690] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)

[2021-06-30 22:00:13.690] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)

{"type":"log","timestamp":"2021-06-30T22:00:13Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}

Output seems to be from speedtest cli, but unsure what the problem.

**Comment by sOblivionsCall** [comment]
@henrywhitaker3 can confirm, i am seeing the exact same issue
```
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2021-07-21 19:00:07.398] [error] Trying to get interface information on non-initialized socket.
[2021-07-21 19:00:12.913] [error] Configuration - Couldn't resolve host name (HostNotFoundException)
[2021-07-21 19:00:12.913] [error] Configuration - Cannot retrieve configuration document (0)
[2021-07-21 19:00:12.914] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
[2021-07-21 19:00:12.914] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
{"type":"log","timestamp":"2021-07-21T19:00:12Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}
```

![image](https://user-images.githubusercontent.com/49297530/126546599-f5ca3fc0-5910-4dbb-877d-72967a909bd9.png)

**Comment by henrywhitaker3** [comment]
Haven't updated the image in ages so can't be that. Have you specified a server Id? Could try doing it without that and see what happens

**Comment by sOblivionsCall** [comment]
@jbrizz please mark this issue with the "Bug" flag

**Comment by sOblivionsCall** [comment]
> Haven't updated the image in ages so can't be that. Have you specified a server Id? Could try doing it without that and see what happens

more than likely something changed in the speedtest cli binary since you have to bootstrap it due to their license

**Comment by Jiriteach** [comment]
Working for me?

**Comment by henrywhitaker3** [comment]
It's throwing a `HostNotFoundException` which makes me think it's a DNS issue - either there's something up with the server you're resolving DNS from, or the DNS record isn't there anymore for a specific server (if you have one specified in the settings)

**Comment by sOblivionsCall** [comment]
> Working for me?

have you tried a fresh container that installs the binary from speedtest? my hunch is that is what is going on

**Comment by sOblivionsCall** [comment]
> It's throwing a `HostNotFoundException` which makes me think it's a DNS issue - either there's something up with the server you're resolving DNS from, or the DNS record isn't there anymore for a specific server (if you have one specified in the settings)

![image](https://user-images.githubusercontent.com/49297530/126547470-a3b1d4bc-6b81-4ff8-8830-4ded42a2131c.png)

messing with things now to check DNS, will report back

**Comment by Jiriteach** [comment]
> > It's throwing a `HostNotFoundException` which makes me think it's a DNS issue - either there's something up with the server you're resolving DNS from, or the DNS record isn't there anymore for a specific server (if you have one specified in the settings)
> 
> ![image](https://user-images.githubusercontent.com/49297530/126547470-a3b1d4bc-6b81-4ff8-8830-4ded42a2131c.png)
> 
> messing with things now to check DNS, will report back

Try a few different servers and also check the DNS you are using.

**Comment by sOblivionsCall** [comment]
hmm, can confirm there is internet connectivity but can't for the life of me figure out what package manager this container has, if one at all. hard to use `dig` without the package haha

**Comment by henrywhitaker3** [comment]
Based on alpine to would be `apk add <package>`

**Comment by sOblivionsCall** [comment]
```
root@speedtest-tracker-59799c9c9d-khc7w:/# apk add bind-tools
fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
ERROR: unable to select packages:
  bind-tools (no such package):
    required by: world[bind-tools]
```
something is definitely sideways with DNS, thanks for this insight @henrywhitaker3 and @Jiriteach . I'll dig into this more after work and figure out what the heck happened.

**Comment by henrywhitaker3** [comment]
Just spun up a fresh instance and works fine for me

**Comment by henrywhitaker3** [comment]
Np - gonna close this issue off but if you tag me/need help still will reply

**Comment by jbrizz** [comment]
DNS is working fine within the container and there is obviously an Internet connection. I've tried specifying a server ID and leaving it blank but the tests still do not run. I'm not really sure where to go from here.

**Comment by sOblivionsCall** [comment]
Something is very broken with my k8's cluster DNS :( No idea what happened here but this should be a fun one to troubleshoot.

From Pod:
```sh
ubectl exec -it hello-wrv4z -- sh                                                                                                                                  ○ lab 14:52:03
/ # dig google.com

; <<>> DiG 9.16.11 <<>> google.com
;; global options: +cmd
;; connection timed out; no servers could be reached

/ # nslookup google.com
;; connection timed out; no servers could be reached


/ # 
command terminated with exit code 1
```

From Host:
```sh
dig google.com

; <<>> DiG 9.16.1-Ubuntu <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25268
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		236	IN	A	74.125.21.101
google.com.		236	IN	A	74.125.21.100
google.com.		236	IN	A	74.125.21.138
google.com.		236	IN	A	74.125.21.113
google.com.		236	IN	A	74.125.21.139
google.com.		236	IN	A	74.125.21.102

;; Query time: 7 msec
;; SERVER: 10.1.1.1#53(10.1.1.1)
;; WHEN: Wed Jul 21 19:54:01 UTC 2021
;; MSG SIZE  rcvd: 135

nslookup google.com
Server:		10.1.1.1
Address:	10.1.1.1#53

Non-authoritative answer:
Name:	google.com
Address: 74.125.21.138
Name:	google.com
Address: 74.125.21.113
Name:	google.com
Address: 74.125.21.139
Name:	google.com
Address: 74.125.21.102
Name:	google.com
Address: 74.125.21.101
Name:	google.com
Address: 74.125.21.100
Name:	google.com
Address: 2607:f8b0:4000:808::200e
```

So nothing to really worry about @henrywhitaker3

**Comment by henrywhitaker3** [comment]
@jbrizz have you tried downloading the binary and running it from the host instead of in the container?

**Comment by jbrizz** [comment]
```root@811acd756487:/# dig google.com

; <<>> DiG 9.16.15 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35056
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             22      IN      A       172.217.167.78

;; Query time: 4 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Jul 21 19:55:21 UTC 2021
;; MSG SIZE  rcvd: 55
```

@henrywhitaker3 nope, not yet.

**Comment by jbrizz** [comment]
```
root@omv:~# speedtest-cli
Retrieving speedtest.net configuration...
Testing from Bigpipe (219.88.234.43)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Spark NZ (Christchurch) [4.39 km]: 6.339 ms
Testing download speed..........................................................                                         ......................
Download: 923.87 Mbit/s
Testing upload speed................................................................................................
Upload: 534.92 Mbit/s
root@omv:~#
```

works fine

**Comment by henrywhitaker3** [comment]
Weird - maybe try just running an alpine container, getting a shell, download the binary and see if it works in that. Can't really think what else it could be

**Comment by sOblivionsCall** [comment]
@henrywhitaker3 the coredns container was "deployed" big time air quotes there.... on a server that is turned off :rofl: . Sorry if i caused alarm earlier
