### ISSUE TITLE
[BUG] 500 - Server error 

### ISSUE THREAD

**Issue by wormvortex** [henrywhitaker3/Speedtest-Tracker#649]
Getting 500 - Server error page only. Was working fine yesterday when I installed it but now al I get is an error page. I've tried to remove and recreate the container but still same issue. 

**Context**
 - OS: Docker
 -  - Speedtest-Tracker Version: speedtest-tracker:latest

There are the logs:

      
         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

-------------------------------------

To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    911

User gid:    911

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 20-config: executing... 

[cont-init.d] 20-config: exited 0.

[cont-init.d] 30-keygen: executing... 

using keys found in /config/keys

[cont-init.d] 30-keygen: exited 0.

[cont-init.d] 40-config: executing... 

Starting 2019/12/30, GeoIP2 databases require personal license key to download. Please manually download/update the GeoIP2 db and save as /config/geoip2db/GeoLite2-City.mmdb

[cont-init.d] 40-config: exited 0.

[cont-init.d] 50-speedtest: executing... 

Copying latest site files to config

Database file exists

Env file exists

Running database migrations

**************************************

*     Application In Production!     *

**************************************

 Do you really wish to run this command? (yes/no) [no]:

 > Command Canceled!

Generating app key

Application key set successfully.

JWT secret exists

Slack webhook is unset

Telegram chat id and bot token unset

Base path is unset

AUTH variable not set. Disabling authentication

Disabling authentication

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `settings` where `name` = auth)

  at /config/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671

    667▕         // If an exception occurs when attempting to run a query, we'll format the error

    668▕         // message to include the bindings with SQL, which will make this exception a

    669▕         // lot more helpful to the developer instead of just the database's errors.

    670▕         catch (Exception $e) {

  ➜ 671▕             throw new QueryException(

    672▕                 $query, $this->prepareBindings($bindings), $e

    673▕             );

    674▕         }

    675▕

      +25 vendor frames 

  26  /config/www/app/Helpers/SettingsHelper.php:21

      Illuminate\Database\Eloquent\Builder::get()

  27  /config/www/app/Helpers/SettingsHelper.php:42

      App\Helpers\SettingsHelper::get()

Clearing old jobs from queue

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] Connection refused (SQL: delete from `jobs`)

  at /config/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:671

    667▕         // If an exception occurs when attempting to run a query, we'll format the error

    668▕         // message to include the bindings with SQL, which will make this exception a

    669▕         // lot more helpful to the developer instead of just the database's errors.

    670▕         catch (Exception $e) {

  ➜ 671▕             throw new QueryException(

    672▕                 $query, $this->prepareBindings($bindings), $e

    673▕             );

    674▕         }

    675▕

      +19 vendor frames 

  20  /config/www/app/Console/Commands/ClearQueueCommand.php:41

      Illuminate\Database\Query\Builder::delete()

      +13 vendor frames 

  34  /config/www/artisan:37

      Illuminate\Foundation\Console\Kernel::handle()

[cont-init.d] 50-speedtest: exited 0.

[cont-init.d] 99-custom-files: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

**Comment by henrywhitaker3** [comment]
You using an external database?

**Comment by wormvortex** [comment]
I didn't specify one. I simply used the docker-compose config below:

ersion: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8765:80
        volumes:
            - /path/to/data:/config
        environment:
            - TZ=
            - PGID=
            - PUID=
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped

**Comment by henrywhitaker3** [comment]
Okay, can you try it without or with a new volume

**Comment by wormvortex** [comment]
Just commented out the line and recreated the container and its working fine. However I don't understand how with the line added it did initially work yesterday?

**Comment by henrywhitaker3** [comment]
It uses a sqlite db by default - must have corrupted somehow
