### ISSUE TITLE
Where is the Dockerfile?

### ISSUE THREAD

**Issue by 5t4cktr4c3** [henrywhitaker3/Speedtest-Tracker#657]
I'm having trouble getting the container started. Doing that interactively I was able to figure out that something fails while installing the Speedtest CLI: `wget: bad address 'install.speedtest.net'`

However, I searched for `install.speedtest.net` in this repository, but I couldn't find any file that contains this request. From somewhere this statements must come.
So I need to guess that it must be in the `Dockerfile`. However, there is no `Dockerfile` in this repository. Where is it?

**Comment by henrywhitaker3** [comment]
Check the `docker` and `dev-docker` branches
