### ISSUE TITLE
[BUG] tar: can't open 'speedtest.tgz': No such file or directory

### ISSUE THREAD

**Issue by samleemc** [henrywhitaker3/Speedtest-Tracker#670]
hi, 

When I install the docker, I got the following error. Any idea what is wrong?

[cont-init.d] 40-config: exited 0.  
[cont-init.d] 50-speedtest: executing...   
Ookla GDPR and EULA accepted. 
Downloading Speedtest CLI.  
wget: bad address 'install.speedtest.net'  
tar: can't open 'speedtest.tgz': No such file or directory  
cp: cannot stat 'speedtest': No such file or directory  
s6-applyuidgid: fatal: unable to exec /site/app/Bin/speedtest: No such file or directory  
Copying latest site files to config

Thanks!
Sam

**Comment by eiger8** [comment]
@henrywhitaker3 please rebuild the docker image as the speedtest cli url updated.

**Comment by henrywhitaker3** [comment]
Gave just updated the `latest` tag now mate - let me know if it's working

**Comment by eiger8** [comment]
Started a fresh container. Everything is working as expected. Thanks for quick response.

**Comment by eiger8** [comment]
@henrywhitaker3 sorry bothering in this tread. After merge speedtest binary is downloading but the dashboard is not functional. 
<img width="1622" alt="Safari 2021-08-29 at 14 01 51" src="https://user-images.githubusercontent.com/21951841/131248212-758f4d88-411f-4fe4-aba8-a36bb852ecf2.png">

**Comment by henrywhitaker3** [comment]
Can u post the docker logs please mate

**Comment by eiger8** [comment]
Here it is 
[Speedtest-ISP.csv](https://github.com/henrywhitaker3/Speedtest-Tracker/files/7072424/Speedtest-ISP.csv)

**Comment by eiger8** [comment]
@henrywhitaker3 looked into logs. It can not download the speedtest.tgz with the error `wget: error getting response: Connection reset by peer`. After further investigation I figured out that wget can not handle https.
When executing `wget http://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-$arch-linux.tgz -O speedtest.tgz` it is able to download the binary. 

Im am running container on Synology NAS wget and docker implementation. Tried to reproduce it on Docker Desktop Mac and it is not reproducible. So the root-cause is in Synology's implementation of dedicated utils.

**Comment by eiger8** [comment]
Would be great to have the info about synology in repo's readme or wiki. Not everyone is tech enough to understand how to resolve that issue.

**Comment by webysther** [comment]
There's a way to fix without doing fancy things on synology:

1) Download the file here: https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-x86_64-linux.tgz
2) Mount a volume to /tmp
2) put the file as speedtest.tgz inside the tmp folder
3) Start container
4) Stop container after work was confirmed
5) Remove /tmp volume
6) Start again
