### ISSUE TITLE
php error after changes made today for latest Docker tag

### ISSUE THREAD

**Issue by jackyaz** [henrywhitaker3/Speedtest-Tracker#676]
PHP Warning:  require(/config/www/vendor/autoload.php): failed to open stream: No such file or directory in /config/www/artisan on line 18

PHP Fatal error:  require(): Failed opening required '/config/www/vendor/autoload.php' (include_path='.:/usr/share/php7') in /config/www/artisan on line 18

**Comment by jackyaz** [comment]
Turns out this was a DNS issue in my set up, all seems OK

**Comment by hegranhox** [comment]
I have the same issue.

**Comment by awirthy** [comment]
> 
> 
> Turns out this was a DNS issue in my set up, all seems OK

I'm having this problem also. How did get it to work for you?
