### ISSUE TITLE
[BUG] Stop working on Synology Docker

### ISSUE THREAD

**Issue by sb84** [henrywhitaker3/Speedtest-Tracker#679]
In Journal i get this.
I try to reinstall, but no effect.
Version 1.12.0

Any suggestions?

`date | stream | content
-- | -- | --
2021-09-01 12:54:00 | stdout | crond[830]: USER root pid 1243 cmd php /config/www/artisan schedule:run >> /config/log/speedtest/cron.log
2021-09-01 12:53:00 | stdout | crond[830]: USER root pid 1193 cmd php /config/www/artisan schedule:run >> /config/log/speedtest/cron.log
2021-09-01 12:52:04 | stdout |  
2021-09-01 12:52:04 | stdout | </html>
2021-09-01 12:52:04 | stdout | </body>
2021-09-01 12:52:04 | stdout | <hr><center>openresty</center>
2021-09-01 12:52:04 | stdout | <center><h1>429 Too Many Requests</h1></center>
2021-09-01 12:52:04 | stdout | <body>
2021-09-01 12:52:04 | stdout | <head><title>429 Too Many Requests</title></head>
2021-09-01 12:52:04 | stdout | <html>
2021-09-01 12:52:04 | stdout |  
2021-09-01 12:52:04 | stdout | [2021-09-01 12:52:04.245] [error] Limit reached:`

**Comment by adamus1red** [comment]
Same on a debian based docker host.

```
speedtest_1  | [2021-09-01 12:00:06.299] [error] Trying to get interface information on non-initialized socket.
speedtest_1  | [2021-09-01 12:00:11.819] [error] Configuration - Couldn't resolve host name (HostNotFoundException)
speedtest_1  | [2021-09-01 12:00:11.819] [error] Configuration - Cannot retrieve configuration document (0)
speedtest_1  | [2021-09-01 12:00:11.819] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
speedtest_1  | [2021-09-01 12:00:11.820] [error] ConfigurationError - Could not retrieve or read configuration (Configuration)
speedtest_1  | {"type":"log","timestamp":"2021-09-01T11:00:11Z","message":"Configuration - Could not retrieve or read configuration (ConfigurationError)","level":"error"}
speedtest_1  | [2021-09-01 13:00:03.023] [error] Limit reached:
speedtest_1  |
speedtest_1  | <html>
speedtest_1  | <head><title>429 Too Many Requests</title></head>
speedtest_1  | <body>
speedtest_1  | <center><h1>429 Too Many Requests</h1></center>
speedtest_1  | <hr><center>openresty</center>
speedtest_1  | </body>
speedtest_1  | </html>
speedtest_1  |
speedtest_1  | [2021-09-01 14:00:03.453] [error] Limit reached:
speedtest_1  |
speedtest_1  | <html>
speedtest_1  | <head><title>429 Too Many Requests</title></head>
speedtest_1  | <body>
speedtest_1  | <center><h1>429 Too Many Requests</h1></center>
speedtest_1  | <hr><center>openresty</center>
speedtest_1  | </body>
speedtest_1  | </html>
```

**Comment by c-hri-s** [comment]
Yep, same here:

```
[2021-09-01 13:35:10.706] [error] Limit reached:
<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>openresty</center>
</body>
</html>

```

**Comment by c-hri-s** [comment]
Seems to be  a issue with speedtest.

If you download https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-x86_64-linux.tgz and run it (which is what the container does), you get the same error.

**Comment by Strugglechen1337** [comment]
Hello, same on unraid Docker

**Comment by Strugglechen1337** [comment]
> Seems to be a issue with speedtest.
> 
> If you download https://install.speedtest.net/app/cli/ookla-speedtest-1.0.0-x86_64-linux.tgz and run it (which is what the container does), you get the same error.

ah okay, so maybe we have to wait

**Comment by c-hri-s** [comment]
Same with Windows, so definitely at Ookla's end:

```
C:\ookla-speedtest-1.0.0-win64>speedtest.exe
[2021-09-01 14:58:38.604] [error] Limit reached:

<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by Strugglechen1337** [comment]
It’s working ! It was Ooklas foult

**Comment by adamus1red** [comment]
FYI you might need to restart your container

**Comment by sb84** [comment]
> 
> 
> FYI you might need to restart your container

As You see above, It was Ooklas fault.
