### ISSUE TITLE
[Feature Request] base path

### ISSUE THREAD

**Issue by aincbe** [henrywhitaker3/Speedtest-Tracker#68]
Love the app, looks very slick and works great. Would be great if we could specify a basepath through the docker environment variables. I can't use url rewriting because the source files use an absolute path ( / vs ./ ) Thanks!

**Comment by henrywhitaker3** [comment]
Hey, give this image a go `henrywhitaker3/speedtest-tracker:dev`. You need to set the environment variable `BASE_PATH` when creating the container.

**Comment by aincbe** [comment]
that's the fastest turnaround I've seen, you're awesome!

recreated with docker-compose using all my previous mounts and its working perfectly now.

**Comment by aincbe** [comment]
as a side note, also update the organizr homepage connection with the new path and it works as well

**Comment by henrywhitaker3** [comment]
Nice one, will use it myself for a few days to make sure it's working properly before closing the issue and pushing to master.

**Comment by aincbe** [comment]
I restarted my server (synology DSM) and speedtest won't restart (its setup using docker-compose) log just shows

-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
-> Executing /entrypoint.d/init.sh
App key found. Skipping app key generation
Slack webhook is unset
sed: can't read .env: No such file or directory

**Comment by henrywhitaker3** [comment]
Okay, I'll have a look into it and try push out a fix in the next few days

**Comment by kzaoaai** [comment]
> Hey, give this image a go `henrywhitaker3/speedtest-tracker:dev`. You need to set the environment variable `BASE_PATH` when creating the container. Shouldn't affect it at all, but you might want to make a backup of your current volume folder just to be safe (or just start from scratch with a new volume)

Confirming that this works with nginx. For anyone looking for the conf (docker-letsencrypt):
```
location /speedtest {
    return 301 $scheme://$host/speedtest/;
}
location ^~ /speedtest/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;
    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /login;

    # enable for Authelia, also enable authelia-server.conf in the default site config
    #include /config/nginx/authelia-location.conf;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app speedtest;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

}
```
``

**Comment by itssomthing** [comment]
Could you allow us to download the speed test log data as a spreadsheet, csv, or even allow us to set up a connection to log the data to Google sheets as well? Excellent app!

**Comment by henrywhitaker3** [comment]
Merged into the `latest` release

**Comment by aincbe** [comment]
the new container from the latest tag is having permission issues. It seems some of the files are owned by a user 911 and others are owned by root. The speed.db is owned by root so the container can't write anything to it. api/speedtest/run results in a 500 error SQLSTATE[HY000]: General error: 8 attempt to write a readonly database

**Comment by henrywhitaker3** [comment]
I'm guessing that'll be because the db was created before the image switched to a different base, I've added a line to the entrypoint script that should fix this. Please can you try re-creating the container using the `dev` tag to see if this fixes the issue.

I need to add it to the readme, but you can set it so the files are owned by whichever user you want by supplying the env variables `PUID` and `PGID`.

**Comment by aincbe** [comment]
recreated with dev tag. Most of the files respect the PUID setting except for the geoipdb2 folder and speed.db which are owned by root. it works fine though, speedtests are run and recorded properly

**Comment by aincbe** [comment]
scratch that, the speed.db gets owned by the PUID user after the speedtest is run so its all working good now!

**Comment by henrywhitaker3** [comment]
Nice one

**Comment by alpe12** [comment]
Please, add a note about the existence of BASE_PATH on docker-hub.
Thanks.
