### ISSUE TITLE
[BUG] UI rendering day change, not changing anymore?

### ISSUE THREAD

**Issue by jaxjexjox** [henrywhitaker3/Speedtest-Tracker#682]
**Describe the bug**::

I used to type "15" in the days field and the graphs would re-render to 15 days.
Or 55 or 14 or whatever etc.
This is no longer working in Chrome or Edge, no idea why.  CTRL-F5, no joy no dice.

**To Reproduce**

Change the days field at the bottom, press enter or tab.

**Expected behavior**

See above.

**Screenshots**

No value

**Context**

Running latest docker edition.
Never had a problem with this previously.
Using Windows 10.
Tried a second PC too, no dice.

**Comment by Sn00zEZA** [comment]
Having this same issue for a while now

**Comment by henrywhitaker3** [comment]
Dupe of #680
