### ISSUE TITLE
Speedtest high fluctiation

### ISSUE THREAD

**Issue by KoMa1012** [henrywhitaker3/Speedtest-Tracker#717]
I'm using the container since yesterday to monitor my internet speed (just in case something ever comes up). But The speed being tested is inaccurate, I've got a 250/50mbit/s (via Vodafone cable in Germany) connection. What I'm currently doing is to run the test every (full) hour, and then validating it with running a speedtest with speedtest.net afterwards. I always get 250/50 (+-5%) via speedtest.net, but the container reports downstream even below 50mbit/s sometimes.
![image](https://user-images.githubusercontent.com/2759494/134128791-46336853-54cc-4724-bac3-f1ef69e45658.png)
I don't know what additional information I can provide, just let me know what to do and I'll do my best to support you on this.

**Comment by tuckshoprn** [comment]
I would try to go for a time not on the exact hour, as test servers can be overwhelmed at these times as everyone picks them.  However this is probably not the reason for your issue.  Can you check which server is selected when you do it manually and then specify that server in the container. This would rule out a bad server selection.

**Comment by tuckshoprn** [comment]
Looking at your graph it does seem to report the full 250 sometimes, so is it possible that as it ran the tests, something else on your network was consuming a large amount of bandwidth, explaining the drop in speed to the test server.  It is unable to stop your other processes while it does the test, so will only report the remaining bandwidth on your connection.

**Comment by KoMa1012** [comment]
Thank you for your response I double checked:
1. Test time changed (I just did a test at :10, :34, :36 and :39) I got max speed at :36 with 260mbit/s and min with 120mbit/s at :34.
2. When I do it manually there was a server selected "Mobile Breitbandnetze GmbH Freisbach"
3. I made sure no one else is using bandwith at that time, it's only me and my wife. Additionally I see the fluctuation at night where we are sleeping (I hope she doesn't netflix without me ;-) ).

**Comment by tuckshoprn** [comment]
It can be any process on your network that uses the internet - for example iOS or Android updates, photo syncing etc. They can be working in the background without your knowledge. But yes it does seem strange that it fluctuates so much.

If you get consistently good result with that manually selected server, find its server ID for the speedtest cli and then specify it as the server to use for the speedtest in docker. It could be that the speedtest cli in the docker container makes a bad choice of server more than it makes a good choice!

**Comment by tuckshoprn** [comment]
That server is is 4462

**Comment by KoMa1012** [comment]
> That server is is 4462
thank you, how did you find this out? I googled it but I only can find a list for US and other countries.

**Comment by tuckshoprn** [comment]
https://williamyaps.github.io/wlmjavascript/servercli.html

**Comment by KoMa1012** [comment]
thank you for your help so far, it seems to have helped! I still see some misbehavior, but it improved significantly. This seems to be sufficient for my needs at the moment.
![image](https://user-images.githubusercontent.com/2759494/135412011-d10f9752-8191-400e-8b6f-95d9009ed351.png)
