### ISSUE TITLE
[BUG] Unable to start Portainer, Rancher or Docker Compose

### ISSUE THREAD

**Issue by ghost** [henrywhitaker3/Speedtest-Tracker#747]
**Describe the bug**
Prevents container starting.
Portainer:
standard_init_linux.go:228: exec user process caused: exec format error

Docker Compose:
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
db1b83ad925273201f6dd568ffa67426434d761e4e91df3e5eea1eff03d85ec3

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a ubuntu server
2. Install docker
3. Try to install speedtest-tracker.

**Expected behaviour**
For the container to start.

**Screenshots**
![image](https://user-images.githubusercontent.com/54777618/138352959-8969f9b3-5ca8-4be8-ae76-c835f7bfe478.png)
![image](https://user-images.githubusercontent.com/54777618/138353023-b260fadc-880c-4c1e-89b7-79f03d023dff.png)

**Context**
 - OS: Ubuntu(20.04.3), Docker, Rancher(2.5.7) Portainer(2.9.1).
 - Speedtest-Tracker Version: 

**Additional context**

**Comment by agneevX** [comment]
Append `latest-arm` to your image (`henrywhitaker3/speedtest-tracker:latest-arm`).

**Comment by ghost** [comment]
Thank you for this fix. This has worked.
