### ISSUE TITLE
After power failure, historical data is gone

### ISSUE THREAD

**Issue by cabotek** [henrywhitaker3/Speedtest-Tracker#782]
Hello, 

Forgive me if this is not a bug, I'm new at using this project. I set it up last night on a VM and a tech this morning power cycled the server. When we rebooted the VM and started the container again, all data from previous speed tests were gone. Is there something in the settings of the GUI I need to configure to make sure the docker container can survive a reboot? Or is there something in the container config I need to add when I run the docker create command?

Much appreciated.

**Comment by tuckshoprn** [comment]
You need to specify a persistent volume to map to /config in the container.  This will persist your data and settings across reboots.

**Comment by cabotek** [comment]
This is the command I ran when I created the container. 

sudo docker create --name=speedtest -p 8765:80 -v /tmp/speedtest:/config -e OOKLA_EULA_GDPR=true --restart unless-stopped henrywhitaker3/speedtest-tracker


I did not actually create a file or directory before I ran a the above. What do I need to do to correct this?

**Comment by cabotek** [comment]
Let me add I also did after create.

sudo docker start speedtest

Thanks

**Comment by tuckshoprn** [comment]
You just need to make sure that “ /tmp/speedtest” is a real folder on your hardware. I tend to make a /docker folder and then put all the persistence volumes in it, so I know where they are. I find that easier. I think if you mount anything under /tmp it will be lost in a reboot, I may be wrong, ymmv.

**Comment by cabotek** [comment]
Awesome. I appreciate the advise. Thank you!
