### ISSUE TITLE
[Feature Request] Download Log Data

### ISSUE THREAD

**Issue by itssomthing** [henrywhitaker3/Speedtest-Tracker#83]
Could you allow us to download the speed test log data as a spreadsheet, csv, or even allow us to set up a connection to log the data to Google sheets as well? Excellent app!

**Comment by henrywhitaker3** [comment]
Yeah CSV should be easy to add, haven't used google sheets before, but will have a look into it. Will do the CSV export/import in the next few days, will comment here when it's up

**Comment by henrywhitaker3** [comment]
CSV backup/restore added in the `dev` branch, or if using docker it's the `dev` image

**Comment by itssomthing** [comment]
Thank you for adding this - it works for me - I also like the restore feature you added as well. When I download the log data, it is a JSON file, and is rather hard to read in notepad. If this can be put into a spreadsheet format it would be much more readable and usable. The ultimate solution would have this speedtest program auto-log results to a Google Sheet so it can be accessed anywhere publicly.

**Comment by henrywhitaker3** [comment]
There should be a CSV backup option there, which can be opened in any spreadhseet client (WPS, libre, excel etc.). I've just seen some php packages for google sheets, so it should be possible, but it might be a while

**Comment by itssomthing** [comment]
Is there somewhere to select CSV option? I only see Download and Restore buttons, and when I click download it gives me the JSON file

**Comment by henrywhitaker3** [comment]
What version number are you running (at the bottom of the webpage) latest version in the dev branch should have both, these backup/restore buttons will then be dropdowns:

![Peek 2020-06-17 19-08](https://user-images.githubusercontent.com/36062479/84933660-247aca80-b0ce-11ea-83d6-ed8463b0767f.gif)

**Comment by itssomthing** [comment]
Got it - I am on 1.5.1 - will try dev branch - thanks for the screenshot!
