### ISSUE TITLE
[BUG] Not Getting results into my telegram bot

### ISSUE THREAD

**Issue by jeedme** [henrywhitaker3/Speedtest-Tracker#866]
**Describe the bug**

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Notification'
3. Telegram Bot token '....'
4. Save & Test Notification

**Expected behavior**
I should get a test result into my telegram bot.

**Screenshots**
![image](https://user-images.githubusercontent.com/15359687/151782835-c792bf1f-92b2-4753-86ca-8f32fcb6555a.png)

**Context**
 - OS: Docker on Synology
 - Speedtest-Tracker Version: 1.12.0

**Comment by jeedme** [comment]
anyone can help ?

**Comment by DedMsk** [comment]
Edit file 
/config/www/resources/js/components/Settings/SettingsIndex.js
Line 20
        var url = 'api/settings/?token=' + window.token;
replace
        var url = 'api/settings/?token=**youtoken**';

**Comment by jeedme** [comment]
it works !! 

thanks
