### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by IamChrisHeX** [henrywhitaker3/Speedtest-Tracker#931]
**Describe the bug**
Server runs but does not produce any output

**To Reproduce**
Running the server

**Expected behavior**
Expect to output on localhost:8765

**Context**
 -  Docker 17.0.50-ce
 - Speedtest-Tracker Version: Docker 19.03.8 on linux, amd64

**Additional context**
From logs the following lines keep repeating:

PHP Warning:  require(/config/www/vendor/autoload.php): failed to open stream: No such file or directory in /config/www/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/config/www/vendor/autoload.php' (include_path='.:/usr/share/php7') in /config/www/artisan on line 18

**Comment by jenschurchill** [comment]
How did you fix this? - Pulling latest from dockerhub I get this exact error.

**Comment by Lammiwinks** [comment]
I get this error too! Any fix?
