### ISSUE TITLE
[BUG] Speedtest issue on FTTH line 2.5/1

### ISSUE THREAD

**Issue by stich86** [henrywhitaker3/Speedtest-Tracker#990]
**Describe the bug**

Looks like that speedtesting running on internal crontab doesn't reach full speed of the line. Launch speedtest manually give always the real speed (just on download)

**To Reproduce**

Run manual speedtest give alwasy full speed

**Expected behavior**

I'm expect that the speedtest should report same speed between scheduled or manually test

**Screenshots**

![image](https://user-images.githubusercontent.com/27808541/172641024-2a4c892d-df79-4d9b-be10-8c9f3ceec55c.png)

the peak speedtest was done manually

**Context**
 - OS: Docker on a Debian VM with 4vCPU+16GB of RAM on ProxMox, container runs with `--net=host` and not limits for CPU\RAM
 - Speedtest-Tracker Version:  1.12.0

**Comment by hucknz** [comment]
I'm seeing the same issue on my FTTH. Speeds were fluctuating all over the place and ping was quite high. 

I've only had a day of testing but the dev container seems like it might be a work-around. Speed tests using the dev container are at or slightly above line speed and ping has dropped from ~18 to ~3ms. It also seems to have fixed the dns bug that I was having where the container couldn't lookup an address when the DNS (pihole or adguard) was on the same host (not using net-host). The dev container is 4 months newer and half the size too. 

I'll keep testing and add a comment if that changes but could be worth trying out for now. Based on recent activity it doesn't look like bugs will be getting fixed in any hurry.

**Comment by stich86** [comment]
hi @hucknz nice findings.

I've recreated the container with dev tag, let's see if it improves

thanks for the tip :)

**Comment by hucknz** [comment]
I'm afraid it didn't last for me :/ 

DNS issues are still resolved so I'll keep using the dev tag but the speedtests and pings have reverted to being all over the place. Must've just been a good run yesterday.

**Comment by spcqike** [comment]
have a look at which server was used. you can check it under "all tests". 
you can create a whitelist of "good servers" in settings.
for me, this resolved the floating results a little bit. but just as long, as the whitelisted servers are not overloaded.

there is a feature request, to not have a whitelist but a blacklist, for slow servers. but....yeah, there is no one to maintain the project :)

**Comment by stich86** [comment]
> have a look at which server was used. you can check it under "all tests". you can create a whitelist of "good servers" in settings. for me, this resolved the floating results a little bit. but just as long, as the whitelisted servers are not overloaded.
> 
> there is a feature request, to not have a whitelist but a blacklist, for slow servers. but....yeah, there is no one to maintain the project :)

i'm using always the same server.. particular issue is only with I don't limit the BW on the container, if there is a cap @1Gbit/s the issue is not happening...

very strange..

**Comment by hucknz** [comment]
I've tried using a whitelist of servers in the past too, it didn't make any difference to my results :/

> i'm using always the same server.. particular issue is only with I don't limit the BW on the container, if there is a cap @1Gbit/s the issue is not happening...

That's odd. Can I ask where are you fixing the bandwidth for the container? I'm seeing this issue on a 1000/500 and a 300/100 fibre line.

**Comment by stich86** [comment]
>
> > i'm using always the same server.. particular issue is only with I don't limit the BW on the container, if there is a cap @1Gbit/s the issue is not happening...
> 
> That's odd. Can I ask where are you fixing the bandwidth for the container? I'm seeing this issue on a 1000/500 and a 300/100 fibre line.

i'm running Docker into a VM on Proxmox. I limit the network card to 120MB/s (so 960mbit/s), in this case speedtest are very linear
