### ISSUE TITLE
Accept GDPR prompt - Speedtest not running

### ISSUE THREAD

**Issue by YanisKyr** [henrywhitaker3/Speedtest-Tracker#995]
Since Tue 7 Jun, my container hasn't run any successful tests. Even though I have `-e OOKLA_EULA_GDPR=true`, the below message appears in the logs.

Any ideas how to accept the new privacy prompt?

```
Ookla collects certain data through Speedtest that may be considered
personally identifiable, such as your IP address, unique device
identifiers or location. Ookla believes it has a legitimate interest
to share this data with internet providers, hardware manufacturers and
industry regulators to help them understand and create a better and
faster internet. For further information including how the data may be
shared, where the data may be transferred and Ookla's contact details,
please see our Privacy Policy at:
       http://www.speedtest.net/privacy
==============================================================================
To accept the message please run speedtest interactively or use the following: 
    speedtest --accept-gdpr
```

**Comment by purpose-pending** [comment]
Same issue, speed tests failed for ~2 days till I noticed. 
Found fix [in a previous issue from a year ago](https://github.com/henrywhitaker3/Speedtest-Tracker/issues/459#issuecomment-771195948), fix works, not sure why it broke now for us.

So @YanisKyr, if you docker exec as root and run `php /config/www/artisan speedtest:eula` - it'll start working again.

**Comment by YanisKyr** [comment]
Good man, thanks for pointing me to the fix. That works now.

Much appreciated!
